// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_team

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TeamDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"has_access": schema.BoolAttribute{
				Computed:           true,
				DeprecationMessage: "This field is deprecated and will be removed in a future version.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique URL slug for this team. **Deprecated** Use `slug` instead.",
				MarkdownDescription: "The unique URL slug for this team. **Deprecated** Use `slug` instead.",
				DeprecationMessage:  "Use `slug` instead.",
			},
			"internal_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal ID for this team.",
				MarkdownDescription: "The internal ID for this team.",
			},
			"is_member": schema.BoolAttribute{
				Computed:           true,
				DeprecationMessage: "This field is deprecated and will be removed in a future version.",
			},
			"is_pending": schema.BoolAttribute{
				Computed:           true,
				DeprecationMessage: "This field is deprecated and will be removed in a future version.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The human readable name for this team.",
				MarkdownDescription: "The human readable name for this team.",
			},
			"organization": schema.StringAttribute{
				Required:            true,
				Description:         "The unique URL slug or internal ID of the organization.",
				MarkdownDescription: "The unique URL slug or internal ID of the organization.",
			},
			"slug": schema.StringAttribute{
				Required:            true,
				Description:         "The unique URL slug for the team.",
				MarkdownDescription: "The unique URL slug for the team.",
			},
		},
		MarkdownDescription: "Sentry Team data source.",
	}
}

type TeamModel struct {
	HasAccess    types.Bool   `tfsdk:"has_access"`
	Id           types.String `tfsdk:"id"`
	InternalId   types.String `tfsdk:"internal_id"`
	IsMember     types.Bool   `tfsdk:"is_member"`
	IsPending    types.Bool   `tfsdk:"is_pending"`
	Name         types.String `tfsdk:"name"`
	Organization types.String `tfsdk:"organization"`
	Slug         types.String `tfsdk:"slug"`
}
