package sentrydata

// https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py#L222-L229
var LogLevels = []string{
	"sample",
	"debug",
	"info",
	"warning",
	"error",
	"fatal",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py#L222-L229
var LogLevelNameToId = map[string]string{
	"sample":  "0",
	"debug":   "10",
	"info":    "20",
	"warning": "30",
	"error":   "40",
	"fatal":   "50",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py#L222-L229
var LogLevelIdToName = map[string]string{
	"0":  "sample",
	"10": "debug",
	"20": "info",
	"30": "warning",
	"40": "error",
	"50": "fatal",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/issues/grouptype.py#L30-L67
var IssueGroupCategories = []string{
	"Error",
	"Performance",
	"Profile",
	"Cron",
	"Replay",
	"Feedback",
	"Uptime",
	"Metric_Alert",
	"Test_Notification",
	"Outage",
	"Metric",
	"Db_Query",
	"Http_Client",
	"Frontend",
	"Mobile",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/issues/grouptype.py#L30-L67
var IssueGroupCategoryNameToId = map[string]string{
	"Error":             "1",
	"Performance":       "2",
	"Profile":           "3",
	"Cron":              "4",
	"Replay":            "5",
	"Feedback":          "6",
	"Uptime":            "7",
	"Metric_Alert":      "8",
	"Test_Notification": "9",
	"Outage":            "10",
	"Metric":            "11",
	"Db_Query":          "12",
	"Http_Client":       "13",
	"Frontend":          "14",
	"Mobile":            "15",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/issues/grouptype.py#L30-L67
var IssueGroupCategoryIdToName = map[string]string{
	"1":  "Error",
	"2":  "Performance",
	"3":  "Profile",
	"4":  "Cron",
	"5":  "Replay",
	"6":  "Feedback",
	"7":  "Uptime",
	"8":  "Metric_Alert",
	"9":  "Test_Notification",
	"10": "Outage",
	"11": "Metric",
	"12": "Db_Query",
	"13": "Http_Client",
	"14": "Frontend",
	"15": "Mobile",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/conditions/event_attribute.py#L41-L72
var EventAttributes = []string{
	"message",
	"platform",
	"environment",
	"type",
	"error.handled",
	"error.unhandled",
	"error.main_thread",
	"exception.type",
	"exception.value",
	"user.id",
	"user.email",
	"user.username",
	"user.ip_address",
	"http.method",
	"http.url",
	"http.status_code",
	"sdk.name",
	"stacktrace.code",
	"stacktrace.module",
	"stacktrace.filename",
	"stacktrace.abs_path",
	"stacktrace.package",
	"unreal.crash_type",
	"app.in_foreground",
	"os.distribution_name",
	"os.distribution_version",
	"symbolicated_in_app",
	"ota_updates.channel",
	"ota_updates.runtime_version",
	"ota_updates.update_id",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py#L6-L22
var MatchTypes = []string{
	"CONTAINS",
	"ENDS_WITH",
	"EQUAL",
	"GREATER_OR_EQUAL",
	"GREATER",
	"IS_SET",
	"IS_IN",
	"LESS_OR_EQUAL",
	"LESS",
	"NOT_CONTAINS",
	"NOT_ENDS_WITH",
	"NOT_EQUAL",
	"NOT_SET",
	"NOT_STARTS_WITH",
	"NOT_IN",
	"STARTS_WITH",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py#L6-L22
var MatchTypeNameToId = map[string]string{
	"CONTAINS":         "co",
	"ENDS_WITH":        "ew",
	"EQUAL":            "eq",
	"GREATER_OR_EQUAL": "gte",
	"GREATER":          "gt",
	"IS_SET":           "is",
	"IS_IN":            "in",
	"LESS_OR_EQUAL":    "lte",
	"LESS":             "lt",
	"NOT_CONTAINS":     "nc",
	"NOT_ENDS_WITH":    "new",
	"NOT_EQUAL":        "ne",
	"NOT_SET":          "ns",
	"NOT_STARTS_WITH":  "nsw",
	"NOT_IN":           "nin",
	"STARTS_WITH":      "sw",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py#L6-L22
var MatchTypeIdToName = map[string]string{
	"co":  "CONTAINS",
	"ew":  "ENDS_WITH",
	"eq":  "EQUAL",
	"gte": "GREATER_OR_EQUAL",
	"gt":  "GREATER",
	"is":  "IS_SET",
	"in":  "IS_IN",
	"lte": "LESS_OR_EQUAL",
	"lt":  "LESS",
	"nc":  "NOT_CONTAINS",
	"new": "NOT_ENDS_WITH",
	"ne":  "NOT_EQUAL",
	"ns":  "NOT_SET",
	"nsw": "NOT_STARTS_WITH",
	"nin": "NOT_IN",
	"sw":  "STARTS_WITH",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py#L25-L29
var LevelMatchTypes = []string{
	"EQUAL",
	"GREATER_OR_EQUAL",
	"LESS_OR_EQUAL",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/models/dashboard_widget.py#L49-L83
var DashboardWidgetTypes = []string{
	"discover",
	"issue",
	"metrics",
	"error-events",
	"transaction-like",
	"spans",
	"logs",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/models/dashboard_widget.py#L133-L150
var DashboardWidgetDisplayTypes = []string{
	"line",
	"area",
	"stacked_area",
	"bar",
	"table",
	"big_number",
	"top_n",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/models/project.py#L62-L167
var Platforms = []string{
	"other",
	"android",
	"apple",
	"apple-ios",
	"apple-macos",
	"bun",
	"capacitor",
	"cordova",
	"dart",
	"deno",
	"dotnet",
	"dotnet-aspnet",
	"dotnet-aspnetcore",
	"dotnet-awslambda",
	"dotnet-gcpfunctions",
	"dotnet-maui",
	"dotnet-uwp",
	"dotnet-winforms",
	"dotnet-wpf",
	"dotnet-xamarin",
	"electron",
	"elixir",
	"flutter",
	"go",
	"go-echo",
	"go-fasthttp",
	"go-fiber",
	"go-gin",
	"go-http",
	"go-iris",
	"go-martini",
	"go-negroni",
	"godot",
	"ionic",
	"java",
	"java-log4j2",
	"java-logback",
	"java-spring",
	"java-spring-boot",
	"javascript",
	"javascript-angular",
	"javascript-astro",
	"javascript-ember",
	"javascript-gatsby",
	"javascript-nextjs",
	"javascript-react",
	"javascript-remix",
	"javascript-solid",
	"javascript-solidstart",
	"javascript-svelte",
	"javascript-sveltekit",
	"javascript-tanstackstart-react",
	"javascript-nuxt",
	"javascript-vue",
	"kotlin",
	"minidump",
	"native",
	"native-qt",
	"nintendo-switch",
	"node",
	"node-awslambda",
	"node-azurefunctions",
	"node-cloudflare-pages",
	"node-cloudflare-workers",
	"node-connect",
	"node-express",
	"node-fastify",
	"node-gcpfunctions",
	"node-hapi",
	"node-koa",
	"node-nestjs",
	"php",
	"php-laravel",
	"php-symfony",
	"powershell",
	"python",
	"python-aiohttp",
	"python-asgi",
	"python-awslambda",
	"python-bottle",
	"python-celery",
	"python-chalice",
	"python-django",
	"python-falcon",
	"python-fastapi",
	"python-flask",
	"python-gcpfunctions",
	"python-pylons",
	"python-pymongo",
	"python-pyramid",
	"python-quart",
	"python-rq",
	"python-sanic",
	"python-serverless",
	"python-starlette",
	"python-tornado",
	"python-tryton",
	"python-wsgi",
	"react-native",
	"ruby",
	"ruby-rack",
	"ruby-rails",
	"rust",
	"unity",
	"unreal",
}
