package sentrydata

// https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py
var LogLevels = []string{
	"sample",
	"debug",
	"info",
	"warning",
	"error",
	"fatal",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py
var LogLevelNameToId = map[string]string{
	"sample":  "0",
	"debug":   "10",
	"info":    "20",
	"warning": "30",
	"error":   "40",
	"fatal":   "50",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/constants.py
var LogLevelIdToName = map[string]string{
	"0":  "sample",
	"10": "debug",
	"20": "info",
	"30": "warning",
	"40": "error",
	"50": "fatal",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/issues/grouptype.py
var IssueGroupCategories = []string{
	"Error",
	"Performance",
	"Profile",
	"Cron",
	"Replay",
	"Feedback",
	"Uptime",
	"Metric_Alert",
	"Test_Notification",
	"Outage",
	"Metric",
	"Db_Query",
	"Http_Client",
	"Frontend",
	"Mobile",
	"Ai_Detected",
	"Preprod",
	"Instrumentation",
	"Configuration",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/issues/grouptype.py
var IssueGroupCategoryNameToId = map[string]string{
	"Error":             "1",
	"Performance":       "2",
	"Profile":           "3",
	"Cron":              "4",
	"Replay":            "5",
	"Feedback":          "6",
	"Uptime":            "7",
	"Metric_Alert":      "8",
	"Test_Notification": "9",
	"Outage":            "10",
	"Metric":            "11",
	"Db_Query":          "12",
	"Http_Client":       "13",
	"Frontend":          "14",
	"Mobile":            "15",
	"Ai_Detected":       "16",
	"Preprod":           "17",
	"Instrumentation":   "18",
	"Configuration":     "19",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/issues/grouptype.py
var IssueGroupCategoryIdToName = map[string]string{
	"1":  "Error",
	"2":  "Performance",
	"3":  "Profile",
	"4":  "Cron",
	"5":  "Replay",
	"6":  "Feedback",
	"7":  "Uptime",
	"8":  "Metric_Alert",
	"9":  "Test_Notification",
	"10": "Outage",
	"11": "Metric",
	"12": "Db_Query",
	"13": "Http_Client",
	"14": "Frontend",
	"15": "Mobile",
	"16": "Ai_Detected",
	"17": "Preprod",
	"18": "Instrumentation",
	"19": "Configuration",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/conditions/event_attribute.py
var EventAttributes = []string{
	"message",
	"platform",
	"environment",
	"type",
	"error.handled",
	"error.unhandled",
	"error.main_thread",
	"exception.type",
	"exception.value",
	"user.id",
	"user.email",
	"user.username",
	"user.ip_address",
	"http.method",
	"http.url",
	"http.status_code",
	"sdk.name",
	"stacktrace.code",
	"stacktrace.module",
	"stacktrace.filename",
	"stacktrace.abs_path",
	"stacktrace.package",
	"unreal.crash_type",
	"app.in_foreground",
	"os.distribution_name",
	"os.distribution_version",
	"symbolicated_in_app",
	"ota_updates.channel",
	"ota_updates.runtime_version",
	"ota_updates.update_id",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py
var MatchTypes = []string{
	"CONTAINS",
	"ENDS_WITH",
	"EQUAL",
	"GREATER_OR_EQUAL",
	"GREATER",
	"IS_SET",
	"IS_IN",
	"LESS_OR_EQUAL",
	"LESS",
	"NOT_CONTAINS",
	"NOT_ENDS_WITH",
	"NOT_EQUAL",
	"NOT_SET",
	"NOT_STARTS_WITH",
	"NOT_IN",
	"STARTS_WITH",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py
var MatchTypeNameToId = map[string]string{
	"CONTAINS":         "co",
	"ENDS_WITH":        "ew",
	"EQUAL":            "eq",
	"GREATER_OR_EQUAL": "gte",
	"GREATER":          "gt",
	"IS_SET":           "is",
	"IS_IN":            "in",
	"LESS_OR_EQUAL":    "lte",
	"LESS":             "lt",
	"NOT_CONTAINS":     "nc",
	"NOT_ENDS_WITH":    "new",
	"NOT_EQUAL":        "ne",
	"NOT_SET":          "ns",
	"NOT_STARTS_WITH":  "nsw",
	"NOT_IN":           "nin",
	"STARTS_WITH":      "sw",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py
var MatchTypeIdToName = map[string]string{
	"co":  "CONTAINS",
	"ew":  "ENDS_WITH",
	"eq":  "EQUAL",
	"gte": "GREATER_OR_EQUAL",
	"gt":  "GREATER",
	"is":  "IS_SET",
	"in":  "IS_IN",
	"lte": "LESS_OR_EQUAL",
	"lt":  "LESS",
	"nc":  "NOT_CONTAINS",
	"new": "NOT_ENDS_WITH",
	"ne":  "NOT_EQUAL",
	"ns":  "NOT_SET",
	"nsw": "NOT_STARTS_WITH",
	"nin": "NOT_IN",
	"sw":  "STARTS_WITH",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/match.py
var LevelMatchTypes = []string{
	"EQUAL",
	"GREATER_OR_EQUAL",
	"LESS_OR_EQUAL",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/models/dashboard_widget.py
var DashboardWidgetTypes = []string{
	"discover",
	"issue",
	"metrics",
	"error-events",
	"transaction-like",
	"spans",
	"logs",
	"tracemetrics",
	"preprod-app-size",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/models/dashboard_widget.py
var DashboardWidgetDisplayTypes = []string{
	"line",
	"area",
	"stacked_area",
	"bar",
	"table",
	"big_number",
	"top_n",
	"details",
	"categorical_bar",
	"wheel",
	"rage_and_dead_clicks",
	"server_tree",
	"text",
	"agents_traces_table",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/models/project.py
var Platforms = []string{
	"other",
	"android",
	"apple",
	"apple-ios",
	"apple-macos",
	"bun",
	"capacitor",
	"cordova",
	"dart",
	"deno",
	"dotnet",
	"dotnet-aspnet",
	"dotnet-aspnetcore",
	"dotnet-awslambda",
	"dotnet-gcpfunctions",
	"dotnet-maui",
	"dotnet-uwp",
	"dotnet-winforms",
	"dotnet-wpf",
	"dotnet-xamarin",
	"electron",
	"elixir",
	"flutter",
	"go",
	"go-echo",
	"go-fasthttp",
	"go-fiber",
	"go-gin",
	"go-http",
	"go-iris",
	"go-martini",
	"go-negroni",
	"godot",
	"ionic",
	"java",
	"java-log4j2",
	"java-logback",
	"java-spring",
	"java-spring-boot",
	"javascript",
	"javascript-angular",
	"javascript-astro",
	"javascript-ember",
	"javascript-gatsby",
	"javascript-nextjs",
	"javascript-nuxt",
	"javascript-react",
	"javascript-react-router",
	"javascript-remix",
	"javascript-solid",
	"javascript-solidstart",
	"javascript-svelte",
	"javascript-sveltekit",
	"javascript-tanstackstart-react",
	"javascript-vue",
	"kotlin",
	"minidump",
	"native",
	"native-qt",
	"nintendo-switch",
	"node",
	"node-awslambda",
	"node-azurefunctions",
	"node-cloudflare-pages",
	"node-cloudflare-workers",
	"node-connect",
	"node-express",
	"node-fastify",
	"node-gcpfunctions",
	"node-hapi",
	"node-hono",
	"node-koa",
	"node-nestjs",
	"php",
	"php-laravel",
	"php-symfony",
	"playstation",
	"powershell",
	"python",
	"python-aiohttp",
	"python-asgi",
	"python-awslambda",
	"python-bottle",
	"python-celery",
	"python-chalice",
	"python-django",
	"python-falcon",
	"python-fastapi",
	"python-flask",
	"python-gcpfunctions",
	"python-pylons",
	"python-pymongo",
	"python-pyramid",
	"python-quart",
	"python-rq",
	"python-sanic",
	"python-serverless",
	"python-starlette",
	"python-tornado",
	"python-tryton",
	"python-wsgi",
	"react-native",
	"ruby",
	"ruby-rack",
	"ruby-rails",
	"rust",
	"unity",
	"unreal",
	"xbox",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/monitors/validators.py
var Intervals = []string{
	"year",
	"month",
	"week",
	"day",
	"hour",
	"minute",
}

var Timezones = []string{
	"Africa/Abidjan",
	"Africa/Accra",
	"Africa/Addis_Ababa",
	"Africa/Algiers",
	"Africa/Asmara",
	"Africa/Asmera",
	"Africa/Bamako",
	"Africa/Bangui",
	"Africa/Banjul",
	"Africa/Bissau",
	"Africa/Blantyre",
	"Africa/Brazzaville",
	"Africa/Bujumbura",
	"Africa/Cairo",
	"Africa/Casablanca",
	"Africa/Ceuta",
	"Africa/Conakry",
	"Africa/Dakar",
	"Africa/Dar_es_Salaam",
	"Africa/Djibouti",
	"Africa/Douala",
	"Africa/El_Aaiun",
	"Africa/Freetown",
	"Africa/Gaborone",
	"Africa/Harare",
	"Africa/Johannesburg",
	"Africa/Juba",
	"Africa/Kampala",
	"Africa/Khartoum",
	"Africa/Kigali",
	"Africa/Kinshasa",
	"Africa/Lagos",
	"Africa/Libreville",
	"Africa/Lome",
	"Africa/Luanda",
	"Africa/Lubumbashi",
	"Africa/Lusaka",
	"Africa/Malabo",
	"Africa/Maputo",
	"Africa/Maseru",
	"Africa/Mbabane",
	"Africa/Mogadishu",
	"Africa/Monrovia",
	"Africa/Nairobi",
	"Africa/Ndjamena",
	"Africa/Niamey",
	"Africa/Nouakchott",
	"Africa/Ouagadougou",
	"Africa/Porto-Novo",
	"Africa/Sao_Tome",
	"Africa/Timbuktu",
	"Africa/Tripoli",
	"Africa/Tunis",
	"Africa/Windhoek",
	"America/Adak",
	"America/Anchorage",
	"America/Anguilla",
	"America/Antigua",
	"America/Araguaina",
	"America/Argentina/Buenos_Aires",
	"America/Argentina/Catamarca",
	"America/Argentina/ComodRivadavia",
	"America/Argentina/Cordoba",
	"America/Argentina/Jujuy",
	"America/Argentina/La_Rioja",
	"America/Argentina/Mendoza",
	"America/Argentina/Rio_Gallegos",
	"America/Argentina/Salta",
	"America/Argentina/San_Juan",
	"America/Argentina/San_Luis",
	"America/Argentina/Tucuman",
	"America/Argentina/Ushuaia",
	"America/Aruba",
	"America/Asuncion",
	"America/Atikokan",
	"America/Atka",
	"America/Bahia",
	"America/Bahia_Banderas",
	"America/Barbados",
	"America/Belem",
	"America/Belize",
	"America/Blanc-Sablon",
	"America/Boa_Vista",
	"America/Bogota",
	"America/Boise",
	"America/Buenos_Aires",
	"America/Cambridge_Bay",
	"America/Campo_Grande",
	"America/Cancun",
	"America/Caracas",
	"America/Catamarca",
	"America/Cayenne",
	"America/Cayman",
	"America/Chicago",
	"America/Chihuahua",
	"America/Ciudad_Juarez",
	"America/Coral_Harbour",
	"America/Cordoba",
	"America/Costa_Rica",
	"America/Coyhaique",
	"America/Creston",
	"America/Cuiaba",
	"America/Curacao",
	"America/Danmarkshavn",
	"America/Dawson",
	"America/Dawson_Creek",
	"America/Denver",
	"America/Detroit",
	"America/Dominica",
	"America/Edmonton",
	"America/Eirunepe",
	"America/El_Salvador",
	"America/Ensenada",
	"America/Fort_Nelson",
	"America/Fort_Wayne",
	"America/Fortaleza",
	"America/Glace_Bay",
	"America/Godthab",
	"America/Goose_Bay",
	"America/Grand_Turk",
	"America/Grenada",
	"America/Guadeloupe",
	"America/Guatemala",
	"America/Guayaquil",
	"America/Guyana",
	"America/Halifax",
	"America/Havana",
	"America/Hermosillo",
	"America/Indiana/Indianapolis",
	"America/Indiana/Knox",
	"America/Indiana/Marengo",
	"America/Indiana/Petersburg",
	"America/Indiana/Tell_City",
	"America/Indiana/Vevay",
	"America/Indiana/Vincennes",
	"America/Indiana/Winamac",
	"America/Indianapolis",
	"America/Inuvik",
	"America/Iqaluit",
	"America/Jamaica",
	"America/Jujuy",
	"America/Juneau",
	"America/Kentucky/Louisville",
	"America/Kentucky/Monticello",
	"America/Knox_IN",
	"America/Kralendijk",
	"America/La_Paz",
	"America/Lima",
	"America/Los_Angeles",
	"America/Louisville",
	"America/Lower_Princes",
	"America/Maceio",
	"America/Managua",
	"America/Manaus",
	"America/Marigot",
	"America/Martinique",
	"America/Matamoros",
	"America/Mazatlan",
	"America/Mendoza",
	"America/Menominee",
	"America/Merida",
	"America/Metlakatla",
	"America/Mexico_City",
	"America/Miquelon",
	"America/Moncton",
	"America/Monterrey",
	"America/Montevideo",
	"America/Montreal",
	"America/Montserrat",
	"America/Nassau",
	"America/New_York",
	"America/Nipigon",
	"America/Nome",
	"America/Noronha",
	"America/North_Dakota/Beulah",
	"America/North_Dakota/Center",
	"America/North_Dakota/New_Salem",
	"America/Nuuk",
	"America/Ojinaga",
	"America/Panama",
	"America/Pangnirtung",
	"America/Paramaribo",
	"America/Phoenix",
	"America/Port-au-Prince",
	"America/Port_of_Spain",
	"America/Porto_Acre",
	"America/Porto_Velho",
	"America/Puerto_Rico",
	"America/Punta_Arenas",
	"America/Rainy_River",
	"America/Rankin_Inlet",
	"America/Recife",
	"America/Regina",
	"America/Resolute",
	"America/Rio_Branco",
	"America/Rosario",
	"America/Santa_Isabel",
	"America/Santarem",
	"America/Santiago",
	"America/Santo_Domingo",
	"America/Sao_Paulo",
	"America/Scoresbysund",
	"America/Shiprock",
	"America/Sitka",
	"America/St_Barthelemy",
	"America/St_Johns",
	"America/St_Kitts",
	"America/St_Lucia",
	"America/St_Thomas",
	"America/St_Vincent",
	"America/Swift_Current",
	"America/Tegucigalpa",
	"America/Thule",
	"America/Thunder_Bay",
	"America/Tijuana",
	"America/Toronto",
	"America/Tortola",
	"America/Vancouver",
	"America/Virgin",
	"America/Whitehorse",
	"America/Winnipeg",
	"America/Yakutat",
	"America/Yellowknife",
	"Antarctica/Casey",
	"Antarctica/Davis",
	"Antarctica/DumontDUrville",
	"Antarctica/Macquarie",
	"Antarctica/Mawson",
	"Antarctica/McMurdo",
	"Antarctica/Palmer",
	"Antarctica/Rothera",
	"Antarctica/South_Pole",
	"Antarctica/Syowa",
	"Antarctica/Troll",
	"Antarctica/Vostok",
	"Arctic/Longyearbyen",
	"Asia/Aden",
	"Asia/Almaty",
	"Asia/Amman",
	"Asia/Anadyr",
	"Asia/Aqtau",
	"Asia/Aqtobe",
	"Asia/Ashgabat",
	"Asia/Ashkhabad",
	"Asia/Atyrau",
	"Asia/Baghdad",
	"Asia/Bahrain",
	"Asia/Baku",
	"Asia/Bangkok",
	"Asia/Barnaul",
	"Asia/Beirut",
	"Asia/Bishkek",
	"Asia/Brunei",
	"Asia/Calcutta",
	"Asia/Chita",
	"Asia/Choibalsan",
	"Asia/Chongqing",
	"Asia/Chungking",
	"Asia/Colombo",
	"Asia/Dacca",
	"Asia/Damascus",
	"Asia/Dhaka",
	"Asia/Dili",
	"Asia/Dubai",
	"Asia/Dushanbe",
	"Asia/Famagusta",
	"Asia/Gaza",
	"Asia/Harbin",
	"Asia/Hebron",
	"Asia/Ho_Chi_Minh",
	"Asia/Hong_Kong",
	"Asia/Hovd",
	"Asia/Irkutsk",
	"Asia/Istanbul",
	"Asia/Jakarta",
	"Asia/Jayapura",
	"Asia/Jerusalem",
	"Asia/Kabul",
	"Asia/Kamchatka",
	"Asia/Karachi",
	"Asia/Kashgar",
	"Asia/Kathmandu",
	"Asia/Katmandu",
	"Asia/Khandyga",
	"Asia/Kolkata",
	"Asia/Krasnoyarsk",
	"Asia/Kuala_Lumpur",
	"Asia/Kuching",
	"Asia/Kuwait",
	"Asia/Macao",
	"Asia/Macau",
	"Asia/Magadan",
	"Asia/Makassar",
	"Asia/Manila",
	"Asia/Muscat",
	"Asia/Nicosia",
	"Asia/Novokuznetsk",
	"Asia/Novosibirsk",
	"Asia/Omsk",
	"Asia/Oral",
	"Asia/Phnom_Penh",
	"Asia/Pontianak",
	"Asia/Pyongyang",
	"Asia/Qatar",
	"Asia/Qostanay",
	"Asia/Qyzylorda",
	"Asia/Rangoon",
	"Asia/Riyadh",
	"Asia/Saigon",
	"Asia/Sakhalin",
	"Asia/Samarkand",
	"Asia/Seoul",
	"Asia/Shanghai",
	"Asia/Singapore",
	"Asia/Srednekolymsk",
	"Asia/Taipei",
	"Asia/Tashkent",
	"Asia/Tbilisi",
	"Asia/Tehran",
	"Asia/Tel_Aviv",
	"Asia/Thimbu",
	"Asia/Thimphu",
	"Asia/Tokyo",
	"Asia/Tomsk",
	"Asia/Ujung_Pandang",
	"Asia/Ulaanbaatar",
	"Asia/Ulan_Bator",
	"Asia/Urumqi",
	"Asia/Ust-Nera",
	"Asia/Vientiane",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yangon",
	"Asia/Yekaterinburg",
	"Asia/Yerevan",
	"Atlantic/Azores",
	"Atlantic/Bermuda",
	"Atlantic/Canary",
	"Atlantic/Cape_Verde",
	"Atlantic/Faeroe",
	"Atlantic/Faroe",
	"Atlantic/Jan_Mayen",
	"Atlantic/Madeira",
	"Atlantic/Reykjavik",
	"Atlantic/South_Georgia",
	"Atlantic/St_Helena",
	"Atlantic/Stanley",
	"Australia/ACT",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Broken_Hill",
	"Australia/Canberra",
	"Australia/Currie",
	"Australia/Darwin",
	"Australia/Eucla",
	"Australia/Hobart",
	"Australia/LHI",
	"Australia/Lindeman",
	"Australia/Lord_Howe",
	"Australia/Melbourne",
	"Australia/NSW",
	"Australia/North",
	"Australia/Perth",
	"Australia/Queensland",
	"Australia/South",
	"Australia/Sydney",
	"Australia/Tasmania",
	"Australia/Victoria",
	"Australia/West",
	"Australia/Yancowinna",
	"Brazil/Acre",
	"Brazil/DeNoronha",
	"Brazil/East",
	"Brazil/West",
	"CET",
	"CST6CDT",
	"Canada/Atlantic",
	"Canada/Central",
	"Canada/Eastern",
	"Canada/Mountain",
	"Canada/Newfoundland",
	"Canada/Pacific",
	"Canada/Saskatchewan",
	"Canada/Yukon",
	"Chile/Continental",
	"Chile/EasterIsland",
	"Cuba",
	"EET",
	"EST",
	"EST5EDT",
	"Egypt",
	"Eire",
	"Etc/GMT",
	"Etc/GMT+0",
	"Etc/GMT+1",
	"Etc/GMT+10",
	"Etc/GMT+11",
	"Etc/GMT+12",
	"Etc/GMT+2",
	"Etc/GMT+3",
	"Etc/GMT+4",
	"Etc/GMT+5",
	"Etc/GMT+6",
	"Etc/GMT+7",
	"Etc/GMT+8",
	"Etc/GMT+9",
	"Etc/GMT-0",
	"Etc/GMT-1",
	"Etc/GMT-10",
	"Etc/GMT-11",
	"Etc/GMT-12",
	"Etc/GMT-13",
	"Etc/GMT-14",
	"Etc/GMT-2",
	"Etc/GMT-3",
	"Etc/GMT-4",
	"Etc/GMT-5",
	"Etc/GMT-6",
	"Etc/GMT-7",
	"Etc/GMT-8",
	"Etc/GMT-9",
	"Etc/GMT0",
	"Etc/Greenwich",
	"Etc/UCT",
	"Etc/UTC",
	"Etc/Universal",
	"Etc/Zulu",
	"Europe/Amsterdam",
	"Europe/Andorra",
	"Europe/Astrakhan",
	"Europe/Athens",
	"Europe/Belfast",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Bratislava",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Busingen",
	"Europe/Chisinau",
	"Europe/Copenhagen",
	"Europe/Dublin",
	"Europe/Gibraltar",
	"Europe/Guernsey",
	"Europe/Helsinki",
	"Europe/Isle_of_Man",
	"Europe/Istanbul",
	"Europe/Jersey",
	"Europe/Kaliningrad",
	"Europe/Kiev",
	"Europe/Kirov",
	"Europe/Kyiv",
	"Europe/Lisbon",
	"Europe/Ljubljana",
	"Europe/London",
	"Europe/Luxembourg",
	"Europe/Madrid",
	"Europe/Malta",
	"Europe/Mariehamn",
	"Europe/Minsk",
	"Europe/Monaco",
	"Europe/Moscow",
	"Europe/Nicosia",
	"Europe/Oslo",
	"Europe/Paris",
	"Europe/Podgorica",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Samara",
	"Europe/San_Marino",
	"Europe/Sarajevo",
	"Europe/Saratov",
	"Europe/Simferopol",
	"Europe/Skopje",
	"Europe/Sofia",
	"Europe/Stockholm",
	"Europe/Tallinn",
	"Europe/Tirane",
	"Europe/Tiraspol",
	"Europe/Ulyanovsk",
	"Europe/Uzhgorod",
	"Europe/Vaduz",
	"Europe/Vatican",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Volgograd",
	"Europe/Warsaw",
	"Europe/Zagreb",
	"Europe/Zaporozhye",
	"Europe/Zurich",
	"GB",
	"GB-Eire",
	"GMT",
	"GMT+0",
	"GMT-0",
	"GMT0",
	"Greenwich",
	"HST",
	"Hongkong",
	"Iceland",
	"Indian/Antananarivo",
	"Indian/Chagos",
	"Indian/Christmas",
	"Indian/Cocos",
	"Indian/Comoro",
	"Indian/Kerguelen",
	"Indian/Mahe",
	"Indian/Maldives",
	"Indian/Mauritius",
	"Indian/Mayotte",
	"Indian/Reunion",
	"Iran",
	"Israel",
	"Jamaica",
	"Japan",
	"Kwajalein",
	"Libya",
	"MET",
	"MST",
	"MST7MDT",
	"Mexico/BajaNorte",
	"Mexico/BajaSur",
	"Mexico/General",
	"NZ",
	"NZ-CHAT",
	"Navajo",
	"PRC",
	"PST8PDT",
	"Pacific/Apia",
	"Pacific/Auckland",
	"Pacific/Bougainville",
	"Pacific/Chatham",
	"Pacific/Chuuk",
	"Pacific/Easter",
	"Pacific/Efate",
	"Pacific/Enderbury",
	"Pacific/Fakaofo",
	"Pacific/Fiji",
	"Pacific/Funafuti",
	"Pacific/Galapagos",
	"Pacific/Gambier",
	"Pacific/Guadalcanal",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Johnston",
	"Pacific/Kanton",
	"Pacific/Kiritimati",
	"Pacific/Kosrae",
	"Pacific/Kwajalein",
	"Pacific/Majuro",
	"Pacific/Marquesas",
	"Pacific/Midway",
	"Pacific/Nauru",
	"Pacific/Niue",
	"Pacific/Norfolk",
	"Pacific/Noumea",
	"Pacific/Pago_Pago",
	"Pacific/Palau",
	"Pacific/Pitcairn",
	"Pacific/Pohnpei",
	"Pacific/Ponape",
	"Pacific/Port_Moresby",
	"Pacific/Rarotonga",
	"Pacific/Saipan",
	"Pacific/Samoa",
	"Pacific/Tahiti",
	"Pacific/Tarawa",
	"Pacific/Tongatapu",
	"Pacific/Truk",
	"Pacific/Wake",
	"Pacific/Wallis",
	"Pacific/Yap",
	"Poland",
	"Portugal",
	"ROC",
	"ROK",
	"Singapore",
	"Turkey",
	"UCT",
	"US/Alaska",
	"US/Aleutian",
	"US/Arizona",
	"US/Central",
	"US/East-Indiana",
	"US/Eastern",
	"US/Hawaii",
	"US/Indiana-Starke",
	"US/Michigan",
	"US/Mountain",
	"US/Pacific",
	"US/Samoa",
	"UTC",
	"Universal",
	"W-SU",
	"WET",
	"Zulu",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/incidents/models/alert_rule.py
var AlertRuleDetectionTypes = []string{
	"static",
	"percent",
	"dynamic",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/uptime/models.py
var UptimeSubscriptionSupportedHttpMethods = []string{
	"GET",
	"POST",
	"HEAD",
	"PUT",
	"DELETE",
	"PATCH",
	"OPTIONS",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/uptime/models.py
var UptimeSubscriptionIntervalSeconds = []int64{
	60,
	300,
	600,
	1200,
	1800,
	3600,
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/uptime/types.py
var UptimeMonitorModes = []string{
	"MANUAL",
	"AUTO_DETECTED_ONBOARDING",
	"AUTO_DETECTED_ACTIVE",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/uptime/types.py
var UptimeMonitorModeNameToId = map[string]int64{
	"MANUAL":                   1,
	"AUTO_DETECTED_ONBOARDING": 2,
	"AUTO_DETECTED_ACTIVE":     3,
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/uptime/types.py
var UptimeMonitorModeIdToName = map[int64]string{
	1: "MANUAL",
	2: "AUTO_DETECTED_ONBOARDING",
	3: "AUTO_DETECTED_ACTIVE",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/snuba/models.py
var SnubaQueryTypes = []string{
	"error",
	"performance",
	"crash_rate",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/snuba/models.py
var SnubaQueryTypeNameToId = map[string]int64{
	"error":       0,
	"performance": 1,
	"crash_rate":  2,
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/snuba/models.py
var SnubaQueryTypeIdToName = map[int64]string{
	0: "error",
	1: "performance",
	2: "crash_rate",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/snuba/models.py
var SnubaExtrapolationModes = []string{
	"unknown",
	"none",
	"client_and_server_weighted",
	"server_weighted",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/snuba/dataset.py
var SnubaDatasets = []string{
	"events",
	"transactions",
	"discover",
	"outcomes",
	"outcomes_raw",
	"sessions",
	"metrics",
	"generic_metrics",
	"replays",
	"profiles",
	"search_issues",
	"functions",
	"spans",
	"events_analytics_platform",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/workflow_engine/models/data_condition.py
var DataConditionTypes = []string{
	"eq",
	"gte",
	"gt",
	"lte",
	"lt",
	"ne",
	"anomaly_detection",
	"age_comparison",
	"assigned_to",
	"event_attribute",
	"event_created_by_detector",
	"event_seen_count",
	"existing_high_priority_issue",
	"first_seen_event",
	"issue_category",
	"issue_occurrences",
	"issue_open_duration",
	"issue_priority_equals",
	"issue_priority_deescalating",
	"issue_priority_greater_or_equal",
	"issue_resolution_change",
	"issue_resolved_trigger",
	"issue_type",
	"latest_adopted_release",
	"latest_release",
	"level",
	"new_high_priority_issue",
	"reappeared_event",
	"regression_event",
	"tagged_event",
	"event_frequency_count",
	"event_frequency_percent",
	"event_unique_user_frequency_count",
	"event_unique_user_frequency_percent",
	"percent_sessions_count",
	"percent_sessions_percent",
	"every_event",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/workflow_engine/models/data_condition.py
var TriggerConditionTypes = []string{
	"first_seen_event",
	"issue_resolved_trigger",
	"reappeared_event",
	"regression_event",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/workflow_engine/models/data_condition_group.py
var DataConditionGroupTypes = []string{
	"any",
	"any-short",
	"all",
	"none",
}

// https://github.com/getsentry/sentry/blob/master/src/sentry/rules/conditions/event_frequency.py
var EventFrequencyStandardIntervals = []string{
	"1m",
	"5m",
	"15m",
	"1h",
	"1d",
	"1w",
	"30d",
}
