openapi: 3.0.0
info:
  title: Sentry API
  version: 0.1.0
servers:
  - url: https://sentry.io/api

paths:
  /0/organizations/{organization_id_or_slug}/:
    get:
      summary: Retrieve an Organization
      operationId: getOrganization
      parameters:
        - name: organization_id_or_slug
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Organization:
      type: object
      required:
        - id
        - name
        - slug
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
