package sentry

// List of valid platform categories
// Taken from: https://github.com/getsentry/sentry/blob/master/src/sentry/utils/platform_categories.py
var platformCategories = []string{
	// Popular
	"javascript",
	"javascript-react",
	"javascript-nextjs",
	"python-django",
	"python",
	"python-flask",
	"python-fastapi",
	"ruby-rails",
	"node-express",
	"php-laravel",
	"java",
	"java-spring-boot",
	"dotnet",
	"dotnet-aspnetcore",
	"csharp",
	"go",
	"php",
	"ruby",
	"node",
	"react-native",
	"javascript-angular",
	"javascript-vue",
	"android",
	"apple-ios",
	"flutter",
	"dart-flutter",
	"unity",

	// Frontend
	"dart",
	"javascript",
	"javascript-react",
	"javascript-angular",
	"javascript-angularjs",
	"javascript-backbone",
	"javascript-ember",
	"javascript-gatsby",
	"javascript-vue",
	"javascript-nextjs",
	"javascript-remix",
	"javascript-svelte",
	"unity",

	// Mobile
	"android",
	"apple-ios",
	"cordova",
	"capacitor",
	"javascript-cordova",
	"javascript-capacitor",
	"ionic",
	"react-native",
	"flutter",
	"dart-flutter",
	"unity",
	"dotnet-maui",
	"dotnet-xamarin",
	"unreal",
	// Old platforms
	"java-android",
	"cocoa-objc",
	"cocoa-swift",

	// Backend
	"dotnet",
	"dotnet-aspnetcore",
	"dotnet-aspnet",
	"elixir",
	"go",
	"go-http",
	"java",
	"java-appengine",
	"java-log4j",
	"java-log4j2",
	"java-logback",
	"java-logging",
	"java-spring",
	"java-spring-boot",
	"native",
	"node",
	"node-express",
	"node-koa",
	"node-connect",
	"perl",
	"php",
	"php-laravel",
	"php-monolog",
	"php-symfony2",
	"python",
	"python-django",
	"python-flask",
	"python-fastapi",
	"python-starlette",
	"python-sanic",
	"python-celery",
	"python-bottle",
	"python-pylons",
	"python-pyramid",
	"python-tornado",
	"python-rq",
	"ruby",
	"ruby-rails",
	"ruby-rack",
	"rust",
	"kotlin",

	// Serverless
	"python-awslambda",
	"python-azurefunctions",
	"python-gcpfunctions",
	"node-awslambda",
	"node-azurefunctions",
	"node-gcpfunctions",
	"dotnet-awslambda",
	"dotnet-gcpfunctions",

	// Desktop
	"apple-macos",
	"dotnet",
	"dotnet-winforms",
	"dotnet-wpf",
	"dotnet-maui",
	"java",
	"electron",
	"javascript-electron",
	"native",
	"native-crashpad",
	"native-breakpad",
	"native-minidump",
	"native-qt",
	"minidump",
	"unity",
	"flutter",
	"kotlin",
	"unreal",

	// Other
	"other",
}
