// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_organization

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OrganizationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique URL slug for this organization. **Deprecated** Use `slug` instead.",
				MarkdownDescription: "The unique URL slug for this organization. **Deprecated** Use `slug` instead.",
				DeprecationMessage:  "Use `slug` instead.",
			},
			"internal_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal ID for this organization.",
				MarkdownDescription: "The internal ID for this organization.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The human readable name for this organization.",
				MarkdownDescription: "The human readable name for this organization.",
			},
			"slug": schema.StringAttribute{
				Required:            true,
				Description:         "The unique URL slug for the organization.",
				MarkdownDescription: "The unique URL slug for the organization.",
			},
		},
		MarkdownDescription: "Sentry Organization data source.",
	}
}

type OrganizationModel struct {
	Id         types.String `tfsdk:"id"`
	InternalId types.String `tfsdk:"internal_id"`
	Name       types.String `tfsdk:"name"`
	Slug       types.String `tfsdk:"slug"`
}
