// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/boolvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &MonitorDataSource{}

func NewMonitorDataSource() datasource.DataSource {
	return &MonitorDataSource{}
}

type MonitorDataSource struct {
	baseDataSource
}

func (d *MonitorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitor"
}

func (d *MonitorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nRetrieve a monitor by ID, or by project and type.\n\nWhen you create a new project, Sentry automatically creates [default monitors](https://docs.sentry.io/product/new-monitors-and-alerts/monitors/#default-monitors). Use the `project` and `type` attributes to retrieve them. The monitor ID can then be used to set up an [alert rule for the monitor](../resources/alert.md).",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "The project slug or internal ID of the monitor. Conflicts with `id`.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("id")),
				},
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Monitor type to retrieve.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("id")),
				},
			},
			"first": schema.BoolAttribute{
				MarkdownDescription: "Return the first monitor found.",
				Optional:            true,
				CustomType:          supertypes.BoolType{},
				Validators: []validator.Bool{
					boolvalidator.ConflictsWith(path.MatchRoot("id")),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the monitor to retrieve. Conflicts with `project`, `type`, and `first`.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("project"), path.MatchRoot("type"), path.MatchRoot("first")),
				},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "The description of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"owner": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MonitorDataSourceModelOwner](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
		},
	}
}

func (d *MonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data MonitorDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(d.read(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type MonitorDataSourceModel struct {
	Organization supertypes.StringValue                                            `tfsdk:"organization"`
	Project      supertypes.StringValue                                            `tfsdk:"project"`
	Type         supertypes.StringValue                                            `tfsdk:"type"`
	First        supertypes.BoolValue                                              `tfsdk:"first"`
	Id           supertypes.StringValue                                            `tfsdk:"id"`
	Enabled      supertypes.BoolValue                                              `tfsdk:"enabled"`
	Name         supertypes.StringValue                                            `tfsdk:"name"`
	Description  supertypes.StringValue                                            `tfsdk:"description"`
	Owner        supertypes.SingleNestedObjectValueOf[MonitorDataSourceModelOwner] `tfsdk:"owner"`
}

func (m *MonitorDataSourceModel) Fill(ctx context.Context, data apiclient.ProjectMonitor) (diags diag.Diagnostics) {
	m.Type = supertypes.NewStringValue(data.Type)
	m.Id = supertypes.NewStringValue(data.Id)
	m.Enabled = supertypes.NewBoolValue(data.Enabled)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Description.Get(); err == nil {
		m.Description = supertypes.NewStringValueOrNull(v)
	} else {
		m.Description = supertypes.NewStringNull()
	}

	if m, ok := any(m).(customFiller[apiclient.ProjectMonitor]); ok {
		diags.Append(m.fill(ctx, data)...)
	}
	return
}

type MonitorDataSourceModelOwner struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}
