// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/go-utils/sliceutils"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &ProjectDataSource{}

func NewProjectDataSource() datasource.DataSource {
	return &ProjectDataSource{}
}

type ProjectDataSource struct {
	baseDataSource
}

func (d *ProjectDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

func (d *ProjectDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a project.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"slug": schema.StringAttribute{
				MarkdownDescription: "The unique URL slug for the project.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"internal_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this project.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of this project.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"platform": schema.StringAttribute{
				MarkdownDescription: "The platform of this project.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"date_created": schema.StringAttribute{
				MarkdownDescription: "The date this project was created.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"features": schema.SetAttribute{
				MarkdownDescription: "The features of this project.",
				Computed:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
			"teams": schema.SetNestedAttribute{
				MarkdownDescription: "The teams of this project.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[ProjectDataSourceModelTeamsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"internal_id": schema.StringAttribute{
							MarkdownDescription: "The internal ID of this team.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of this team.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"slug": schema.StringAttribute{
							MarkdownDescription: "The slug of this team.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique URL slug for this project. **Deprecated** Use `slug` instead.",
				DeprecationMessage:  "Use `slug` instead.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
		},
	}
}

func (d *ProjectDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.apiClient.GetOrganizationProjectWithResponse(ctx, data.Organization.ValueString(), data.Slug.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectDataSourceModel struct {
	Organization supertypes.StringValue                                             `tfsdk:"organization"`
	Slug         supertypes.StringValue                                             `tfsdk:"slug"`
	InternalId   supertypes.StringValue                                             `tfsdk:"internal_id"`
	Name         supertypes.StringValue                                             `tfsdk:"name"`
	Platform     supertypes.StringValue                                             `tfsdk:"platform"`
	DateCreated  supertypes.StringValue                                             `tfsdk:"date_created"`
	Features     supertypes.SetValueOf[string]                                      `tfsdk:"features"`
	Teams        supertypes.SetNestedObjectValueOf[ProjectDataSourceModelTeamsItem] `tfsdk:"teams"`
	Id           supertypes.StringValue                                             `tfsdk:"id"`
}

func (m *ProjectDataSourceModel) Fill(ctx context.Context, data apiclient.Project) (diags diag.Diagnostics) {
	m.Organization = supertypes.NewStringValue(data.Organization.Slug)
	m.Slug = supertypes.NewStringValue(data.Slug)
	m.InternalId = supertypes.NewStringValue(data.Id)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Platform.Get(); err == nil {
		m.Platform = supertypes.NewStringValueOrNull(v)
	} else {
		m.Platform = supertypes.NewStringNull()
	}
	m.DateCreated = supertypes.NewStringValue(data.DateCreated.String())
	m.Features = supertypes.NewSetValueOfSlice(ctx, data.Features)
	m.Teams = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, sliceutils.Map(func(item apiclient.Team) ProjectDataSourceModelTeamsItem {
		var model ProjectDataSourceModelTeamsItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}, data.Teams))
	m.Id = supertypes.NewStringValue(data.Slug) // Deprecated
	return
}

type ProjectDataSourceModelTeamsItem struct {
	InternalId supertypes.StringValue `tfsdk:"internal_id"`
	Name       supertypes.StringValue `tfsdk:"name"`
	Slug       supertypes.StringValue `tfsdk:"slug"`
}

func (m *ProjectDataSourceModelTeamsItem) Fill(ctx context.Context, data apiclient.Team) (diags diag.Diagnostics) {
	m.InternalId = supertypes.NewStringValue(data.Id)
	m.Name = supertypes.NewStringValue(data.Name)
	m.Slug = supertypes.NewStringValue(data.Slug)
	return
}
