// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ = supertypes.StringType{}
var _ datasource.DataSource = &TeamDataSource{}

func NewTeamDataSource() datasource.DataSource {
	return &TeamDataSource{}
}

type TeamDataSource struct {
	baseDataSource
}

func (d *TeamDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_team"
}

func (d *TeamDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a Team",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the organization.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"slug": schema.StringAttribute{
				MarkdownDescription: "The team slug.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique URL slug for this team. **Deprecated** Use `slug` instead.",
				DeprecationMessage:  "Use `slug` instead.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"has_access": schema.BoolAttribute{
				MarkdownDescription: "Whether the API key user has access to this team. **Deprecated** This field is deprecated and will be removed in a future version.",
				DeprecationMessage:  "This field is deprecated and will be removed in a future version.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"internal_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID for this team.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"is_member": schema.BoolAttribute{
				MarkdownDescription: "Whether the API key user is a member of this team. **Deprecated** This field is deprecated and will be removed in a future version.",
				DeprecationMessage:  "This field is deprecated and will be removed in a future version.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"is_pending": schema.BoolAttribute{
				MarkdownDescription: "Whether the API key user is pending on this team. **Deprecated** This field is deprecated and will be removed in a future version.",
				DeprecationMessage:  "This field is deprecated and will be removed in a future version.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The human readable name for this team.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
		},
	}
}

func (d *TeamDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data TeamDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.apiClient.GetOrganizationTeamWithResponse(ctx, data.Organization.ValueString(), data.Slug.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type TeamDataSourceModel struct {
	Organization supertypes.StringValue `tfsdk:"organization"`
	Slug         supertypes.StringValue `tfsdk:"slug"`
	Id           supertypes.StringValue `tfsdk:"id"`
	HasAccess    supertypes.BoolValue   `tfsdk:"has_access"`
	InternalId   supertypes.StringValue `tfsdk:"internal_id"`
	IsMember     supertypes.BoolValue   `tfsdk:"is_member"`
	IsPending    supertypes.BoolValue   `tfsdk:"is_pending"`
	Name         supertypes.StringValue `tfsdk:"name"`
}
