// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &MetricMonitorDataSource{}

func NewMetricMonitorDataSource() datasource.DataSource {
	return &MetricMonitorDataSource{}
}

type MetricMonitorDataSource struct {
	baseDataSource
}

func (d *MetricMonitorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_metric_monitor"
}

func (d *MetricMonitorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nRetrieve a Metric Monitor for a Project.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the project this monitor belongs to.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "The description of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"owner": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MetricMonitorDataSourceModelOwner](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
			"aggregate": schema.StringAttribute{
				MarkdownDescription: "Aggregate query to run on the metric.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"dataset": schema.StringAttribute{
				MarkdownDescription: "Dataset to run the aggregate query on.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"environment": schema.StringAttribute{
				MarkdownDescription: "Environment to run the aggregate query on.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"event_types": schema.SetAttribute{
				MarkdownDescription: "Event types to run the aggregate query on.",
				Computed:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
			"query": schema.StringAttribute{
				MarkdownDescription: "An event search query to subscribe to and monitor for alerts.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"query_type": schema.StringAttribute{
				MarkdownDescription: "The type of query.`",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"time_window_seconds": schema.Int64Attribute{
				MarkdownDescription: "The time window in seconds to use for the aggregate query.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"extrapolation_mode": schema.StringAttribute{
				MarkdownDescription: "Extrapolation mode to use for the aggregate query.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"issue_detection": schema.SingleNestedAttribute{
				MarkdownDescription: "The issue detection type configuration.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MetricMonitorDataSourceModelIssueDetection](ctx),
				Attributes: map[string]schema.Attribute{
					"type": schema.StringAttribute{
						MarkdownDescription: "`static`: Threshold based monitor; `percent`: Change based monitor; `dynamic`: Dynamic monitor.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"comparison_delta": schema.Int64Attribute{
						MarkdownDescription: "The comparison delta in seconds to use for the aggregate query. Only available for `percent` type.",
						Computed:            true,
						CustomType:          supertypes.Int64Type{},
					},
				},
			},
			"condition_group": schema.SingleNestedAttribute{
				MarkdownDescription: "Issue detection condition group configuration.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MetricMonitorDataSourceModelConditionGroup](ctx),
				Attributes: map[string]schema.Attribute{
					"logic_type": schema.StringAttribute{
						MarkdownDescription: "The logic to apply to the conditions. `any` will evaluate all conditions, and return true if any of those are met. `any-short` will stop evaluating conditions as soon as one is met. `all` will evaluate all conditions, and return true if all of those are met. `none` will return true if none of the conditions are met, will return false immediately if any are met.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"conditions": schema.ListNestedAttribute{
						MarkdownDescription: "Issue detection conditions.",
						Computed:            true,
						CustomType:          supertypes.NewListNestedObjectTypeOf[MetricMonitorDataSourceModelConditionGroupConditionsItem](ctx),
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"type": schema.StringAttribute{
									MarkdownDescription: "The type of condition.",
									Computed:            true,
									CustomType:          supertypes.StringType{},
								},
								"comparison": schema.Int64Attribute{
									MarkdownDescription: "The value to compare against. Only available for types other than `anomaly_detection`.",
									Computed:            true,
									CustomType:          supertypes.Int64Type{},
								},
								"comparison_sensitivity": schema.StringAttribute{
									MarkdownDescription: "Level of anomaly responsiveness. Higher thresholds means alerts for most anomalies. Lower thresholds means alerts only for larger ones. Only available for `anomaly_detection` type.",
									Computed:            true,
									CustomType:          supertypes.StringType{},
								},
								"comparison_threshold_type": schema.StringAttribute{
									MarkdownDescription: "Alert to anomalies that are moving above, below, or in both directions in relation to your threshold. Only available for `anomaly_detection` type.",
									Computed:            true,
									CustomType:          supertypes.StringType{},
								},
								"condition_result": schema.Int64Attribute{
									MarkdownDescription: "When the condition is met, the result will be set to this value.",
									Computed:            true,
									CustomType:          supertypes.Int64Type{},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (d *MetricMonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data MetricMonitorDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.apiClient.GetProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type MetricMonitorDataSourceModel struct {
	Organization      supertypes.StringValue                                                           `tfsdk:"organization"`
	Id                supertypes.StringValue                                                           `tfsdk:"id"`
	ProjectId         supertypes.StringValue                                                           `tfsdk:"project_id"`
	Enabled           supertypes.BoolValue                                                             `tfsdk:"enabled"`
	Name              supertypes.StringValue                                                           `tfsdk:"name"`
	Description       supertypes.StringValue                                                           `tfsdk:"description"`
	Owner             supertypes.SingleNestedObjectValueOf[MetricMonitorDataSourceModelOwner]          `tfsdk:"owner"`
	Aggregate         supertypes.StringValue                                                           `tfsdk:"aggregate"`
	Dataset           supertypes.StringValue                                                           `tfsdk:"dataset"`
	Environment       supertypes.StringValue                                                           `tfsdk:"environment"`
	EventTypes        supertypes.SetValueOf[string]                                                    `tfsdk:"event_types"`
	Query             supertypes.StringValue                                                           `tfsdk:"query"`
	QueryType         supertypes.StringValue                                                           `tfsdk:"query_type"`
	TimeWindowSeconds supertypes.Int64Value                                                            `tfsdk:"time_window_seconds"`
	ExtrapolationMode supertypes.StringValue                                                           `tfsdk:"extrapolation_mode"`
	IssueDetection    supertypes.SingleNestedObjectValueOf[MetricMonitorDataSourceModelIssueDetection] `tfsdk:"issue_detection"`
	ConditionGroup    supertypes.SingleNestedObjectValueOf[MetricMonitorDataSourceModelConditionGroup] `tfsdk:"condition_group"`
}

func (m *MetricMonitorDataSourceModel) Fill(ctx context.Context, data apiclient.ProjectMonitor) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(data.Id)
	m.ProjectId = supertypes.NewStringValue(data.ProjectId)
	m.Enabled = supertypes.NewBoolValue(data.Enabled)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Description.Get(); err == nil {
		m.Description = supertypes.NewStringValueOrNull(v)
	} else {
		m.Description = supertypes.NewStringNull()
	}

	if m, ok := any(m).(customFiller[apiclient.ProjectMonitor]); ok {
		diags.Append(m.fill(ctx, data)...)
	}
	return
}

type MetricMonitorDataSourceModelOwner struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}

type MetricMonitorDataSourceModelIssueDetection struct {
	Type            supertypes.StringValue `tfsdk:"type"`
	ComparisonDelta supertypes.Int64Value  `tfsdk:"comparison_delta"`
}

type MetricMonitorDataSourceModelConditionGroup struct {
	LogicType  supertypes.StringValue                                                                       `tfsdk:"logic_type"`
	Conditions supertypes.ListNestedObjectValueOf[MetricMonitorDataSourceModelConditionGroupConditionsItem] `tfsdk:"conditions"`
}

type MetricMonitorDataSourceModelConditionGroupConditionsItem struct {
	Type                    supertypes.StringValue `tfsdk:"type"`
	Comparison              supertypes.Int64Value  `tfsdk:"comparison"`
	ComparisonSensitivity   supertypes.StringValue `tfsdk:"comparison_sensitivity"`
	ComparisonThresholdType supertypes.StringValue `tfsdk:"comparison_threshold_type"`
	ConditionResult         supertypes.Int64Value  `tfsdk:"condition_result"`
}
