// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &CronMonitorDataSource{}

func NewCronMonitorDataSource() datasource.DataSource {
	return &CronMonitorDataSource{}
}

type CronMonitorDataSource struct {
	baseDataSource
}

func (d *CronMonitorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cron_monitor"
}

func (d *CronMonitorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nRetrieve a Cron Monitor.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the project this monitor belongs to.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "The description of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"owner": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[CronMonitorDataSourceModelOwner](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
			"checkin_margin_minutes": schema.Int64Attribute{
				MarkdownDescription: "Grace period. The number of minutes before a check-in is considered missed.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"failure_issue_threshold": schema.Int64Attribute{
				MarkdownDescription: "Failure tolerance. Create a new issue when this many consecutive missed or error check-ins are processed.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"max_runtime_minutes": schema.Int64Attribute{
				MarkdownDescription: "Maximum runtime. The number of minutes before an in-progress check-in is marked timed out.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"recovery_threshold": schema.Int64Attribute{
				MarkdownDescription: "Recovery Tolerance. Resolve the issue when this many consecutive healthy check-ins are processed. Either `crontab` or `interval_value` and `interval_unit` must be provided.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"schedule": schema.SingleNestedAttribute{
				MarkdownDescription: "Schedule for the cron monitor.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[CronMonitorDataSourceModelSchedule](ctx),
				Attributes: map[string]schema.Attribute{
					"crontab": schema.StringAttribute{
						MarkdownDescription: "Crontab expression for the cron monitor.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"interval_value": schema.Int64Attribute{
						MarkdownDescription: "Interval value for the cron monitor.",
						Computed:            true,
						CustomType:          supertypes.Int64Type{},
					},
					"interval_unit": schema.StringAttribute{
						MarkdownDescription: "Interval unit for the cron monitor.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
			"timezone": schema.StringAttribute{
				MarkdownDescription: "The timezone of the cron monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
		},
	}
}

func (d *CronMonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data CronMonitorDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.apiClient.GetProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type CronMonitorDataSourceModel struct {
	Organization          supertypes.StringValue                                                   `tfsdk:"organization"`
	Id                    supertypes.StringValue                                                   `tfsdk:"id"`
	ProjectId             supertypes.StringValue                                                   `tfsdk:"project_id"`
	Enabled               supertypes.BoolValue                                                     `tfsdk:"enabled"`
	Name                  supertypes.StringValue                                                   `tfsdk:"name"`
	Description           supertypes.StringValue                                                   `tfsdk:"description"`
	Owner                 supertypes.SingleNestedObjectValueOf[CronMonitorDataSourceModelOwner]    `tfsdk:"owner"`
	CheckinMarginMinutes  supertypes.Int64Value                                                    `tfsdk:"checkin_margin_minutes"`
	FailureIssueThreshold supertypes.Int64Value                                                    `tfsdk:"failure_issue_threshold"`
	MaxRuntimeMinutes     supertypes.Int64Value                                                    `tfsdk:"max_runtime_minutes"`
	RecoveryThreshold     supertypes.Int64Value                                                    `tfsdk:"recovery_threshold"`
	Schedule              supertypes.SingleNestedObjectValueOf[CronMonitorDataSourceModelSchedule] `tfsdk:"schedule"`
	Timezone              supertypes.StringValue                                                   `tfsdk:"timezone"`
}

func (m *CronMonitorDataSourceModel) Fill(ctx context.Context, data apiclient.ProjectMonitor) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(data.Id)
	m.ProjectId = supertypes.NewStringValue(data.ProjectId)
	m.Enabled = supertypes.NewBoolValue(data.Enabled)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Description.Get(); err == nil {
		m.Description = supertypes.NewStringValueOrNull(v)
	} else {
		m.Description = supertypes.NewStringNull()
	}

	if m, ok := any(m).(customFiller[apiclient.ProjectMonitor]); ok {
		diags.Append(m.fill(ctx, data)...)
	}
	return
}

type CronMonitorDataSourceModelOwner struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}

type CronMonitorDataSourceModelSchedule struct {
	Crontab       supertypes.StringValue `tfsdk:"crontab"`
	IntervalValue supertypes.Int64Value  `tfsdk:"interval_value"`
	IntervalUnit  supertypes.StringValue `tfsdk:"interval_unit"`
}
