// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &UptimeMonitorDataSource{}

func NewUptimeMonitorDataSource() datasource.DataSource {
	return &UptimeMonitorDataSource{}
}

type UptimeMonitorDataSource struct {
	baseDataSource
}

func (d *UptimeMonitorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uptime_monitor"
}

func (d *UptimeMonitorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nRetrieve an Uptime Monitor for a Project.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the project this monitor belongs to.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "The description of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"owner": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[UptimeMonitorDataSourceModelOwner](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
			"url": schema.StringAttribute{
				MarkdownDescription: "The URL to monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"method": schema.StringAttribute{
				MarkdownDescription: "The HTTP method to use for the request.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"body": schema.StringAttribute{
				MarkdownDescription: "The request body to send. Only applicable for methods that support a body.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"headers": schema.MapAttribute{
				MarkdownDescription: "The headers to send with the request.",
				Computed:            true,
				CustomType:          supertypes.NewMapTypeOf[string](ctx),
			},
			"interval_seconds": schema.Int64Attribute{
				MarkdownDescription: "The amount of time between each uptime check request.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"timeout_ms": schema.Int64Attribute{
				MarkdownDescription: "The request timeout in milliseconds.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"environment": schema.StringAttribute{
				MarkdownDescription: "Name of the environment to create uptime issues in.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"recovery_threshold": schema.Int64Attribute{
				MarkdownDescription: "Number of consecutive successful checks required to mark monitor as recovered.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"downtime_threshold": schema.Int64Attribute{
				MarkdownDescription: "Number of consecutive failed checks required to mark monitor as down.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"assertion_json": schema.StringAttribute{
				MarkdownDescription: "Define conditions that must be met for the check to be considered successful.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
		},
	}
}

func (d *UptimeMonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data UptimeMonitorDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.apiClient.GetProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type UptimeMonitorDataSourceModel struct {
	Organization      supertypes.StringValue                                                  `tfsdk:"organization"`
	Id                supertypes.StringValue                                                  `tfsdk:"id"`
	ProjectId         supertypes.StringValue                                                  `tfsdk:"project_id"`
	Enabled           supertypes.BoolValue                                                    `tfsdk:"enabled"`
	Name              supertypes.StringValue                                                  `tfsdk:"name"`
	Description       supertypes.StringValue                                                  `tfsdk:"description"`
	Owner             supertypes.SingleNestedObjectValueOf[UptimeMonitorDataSourceModelOwner] `tfsdk:"owner"`
	Url               supertypes.StringValue                                                  `tfsdk:"url"`
	Method            supertypes.StringValue                                                  `tfsdk:"method"`
	Body              supertypes.StringValue                                                  `tfsdk:"body"`
	Headers           supertypes.MapValueOf[string]                                           `tfsdk:"headers"`
	IntervalSeconds   supertypes.Int64Value                                                   `tfsdk:"interval_seconds"`
	TimeoutMs         supertypes.Int64Value                                                   `tfsdk:"timeout_ms"`
	Environment       supertypes.StringValue                                                  `tfsdk:"environment"`
	RecoveryThreshold supertypes.Int64Value                                                   `tfsdk:"recovery_threshold"`
	DowntimeThreshold supertypes.Int64Value                                                   `tfsdk:"downtime_threshold"`
	AssertionJson     supertypes.StringValue                                                  `tfsdk:"assertion_json"`
}

func (m *UptimeMonitorDataSourceModel) Fill(ctx context.Context, data apiclient.ProjectMonitor) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(data.Id)
	m.ProjectId = supertypes.NewStringValue(data.ProjectId)
	m.Enabled = supertypes.NewBoolValue(data.Enabled)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Description.Get(); err == nil {
		m.Description = supertypes.NewStringValueOrNull(v)
	} else {
		m.Description = supertypes.NewStringNull()
	}

	if m, ok := any(m).(customFiller[apiclient.ProjectMonitor]); ok {
		diags.Append(m.fill(ctx, data)...)
	}
	return
}

type UptimeMonitorDataSourceModelOwner struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}
