// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ = supertypes.StringType{}
var _ datasource.DataSource = &ProjectIssueStreamMonitorDataSource{}

func NewProjectIssueStreamMonitorDataSource() datasource.DataSource {
	return &ProjectIssueStreamMonitorDataSource{}
}

type ProjectIssueStreamMonitorDataSource struct {
	baseDataSource
}

func (d *ProjectIssueStreamMonitorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_issue_stream_monitor"
}

func (d *ProjectIssueStreamMonitorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve a Project Issue Stream Monitor by project ID or slug. This is helpful for managing [default monitors](https://docs.sentry.io/product/new-monitors-and-alerts/monitors/#default-monitors) that were created by Sentry outside of Terraform. You can then map these IDs into `sentry_alert.monitor_ids` to define [alert rules](../resources/alert.md) for those monitors.\n\n**Note:** When multiple monitors are found, the `first` attribute can be set to `true` to return the first monitor found. If `first` is not set to `true` and multiple monitors are found, the data source will return an error.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "The project slug or internal ID of the monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"first": schema.BoolAttribute{
				MarkdownDescription: "Return the first monitor found.",
				Optional:            true,
				CustomType:          supertypes.BoolType{},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "The description of the monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"owner": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[ProjectIssueStreamMonitorDataSourceModelOwner](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
		},
	}
}

func (d *ProjectIssueStreamMonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectIssueStreamMonitorDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(d.read(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectIssueStreamMonitorDataSourceModel struct {
	Organization supertypes.StringValue                                                              `tfsdk:"organization"`
	Project      supertypes.StringValue                                                              `tfsdk:"project"`
	First        supertypes.BoolValue                                                                `tfsdk:"first"`
	Id           supertypes.StringValue                                                              `tfsdk:"id"`
	Enabled      supertypes.BoolValue                                                                `tfsdk:"enabled"`
	Name         supertypes.StringValue                                                              `tfsdk:"name"`
	Description  supertypes.StringValue                                                              `tfsdk:"description"`
	Owner        supertypes.SingleNestedObjectValueOf[ProjectIssueStreamMonitorDataSourceModelOwner] `tfsdk:"owner"`
}

func (m *ProjectIssueStreamMonitorDataSourceModel) Fill(ctx context.Context, data apiclient.ProjectMonitor) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(data.Id)
	m.Enabled = supertypes.NewBoolValue(data.Enabled)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Description.Get(); err == nil {
		m.Description = supertypes.NewStringValueOrNull(v)
	} else {
		m.Description = supertypes.NewStringNull()
	}

	if m, ok := any(m).(customFiller[apiclient.ProjectMonitor]); ok {
		diags.Append(m.fill(ctx, data)...)
	}
	return
}

type ProjectIssueStreamMonitorDataSourceModelOwner struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}
