// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/go-utils/sliceutils"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	"github.com/jianyuan/terraform-provider-sentry/internal/sentryclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &AllProjectsDataSource{}

func NewAllProjectsDataSource() datasource.DataSource {
	return &AllProjectsDataSource{}
}

type AllProjectsDataSource struct {
	baseDataSource
}

func (d *AllProjectsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_all_projects"
}

func (d *AllProjectsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List of projects in an organization.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID to list projects for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"project_slugs": schema.SetAttribute{
				MarkdownDescription: "The set of project slugs in this organization. **Deprecated** Use `projects[*].slug` instead.",
				DeprecationMessage:  "Use `projects[*].slug` instead.",
				Computed:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
			"projects": schema.SetNestedAttribute{
				MarkdownDescription: "The projects in this organization.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[AllProjectsDataSourceModelProjectsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"slug": schema.StringAttribute{
							MarkdownDescription: "The unique URL slug for the project.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"internal_id": schema.StringAttribute{
							MarkdownDescription: "The internal ID of this project.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of this project.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"platform": schema.StringAttribute{
							MarkdownDescription: "The platform of this project.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"color": schema.StringAttribute{
							MarkdownDescription: "The color of this project.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"date_created": schema.StringAttribute{
							MarkdownDescription: "The date this project was created.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"features": schema.SetAttribute{
							MarkdownDescription: "The features of this project.",
							Computed:            true,
							CustomType:          supertypes.NewSetTypeOf[string](ctx),
						},
						"teams": schema.SetNestedAttribute{
							MarkdownDescription: "The teams of this project.",
							Computed:            true,
							CustomType:          supertypes.NewSetNestedObjectTypeOf[AllProjectsDataSourceModelProjectsItemTeamsItem](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"internal_id": schema.StringAttribute{
										MarkdownDescription: "The internal ID of this team.",
										Computed:            true,
										CustomType:          supertypes.StringType{},
									},
									"name": schema.StringAttribute{
										MarkdownDescription: "The name of this team.",
										Computed:            true,
										CustomType:          supertypes.StringType{},
									},
									"slug": schema.StringAttribute{
										MarkdownDescription: "The slug of this team.",
										Computed:            true,
										CustomType:          supertypes.StringType{},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (d *AllProjectsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data AllProjectsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.Project
	params := &apiclient.ListOrganizationProjectsParams{}

	for {

		httpResp, err := d.apiClient.ListOrganizationProjectsWithResponse(ctx, data.Organization.ValueString(), params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, *httpResp.JSON200...)

		params.Cursor = sentryclient.ParseNextPaginationCursor(httpResp.HTTPResponse)
		if params.Cursor == nil {
			break
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type AllProjectsDataSourceModel struct {
	Organization supertypes.StringValue                                                    `tfsdk:"organization"`
	ProjectSlugs supertypes.SetValueOf[string]                                             `tfsdk:"project_slugs"`
	Projects     supertypes.SetNestedObjectValueOf[AllProjectsDataSourceModelProjectsItem] `tfsdk:"projects"`
}

func (m *AllProjectsDataSourceModel) Fill(ctx context.Context, data []apiclient.Project) (diags diag.Diagnostics) {
	m.ProjectSlugs = supertypes.NewSetValueOfSlice(ctx, sliceutils.Map(func(item apiclient.Project) string {
		return item.Slug
	}, data)) // Deprecated
	m.Projects = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, sliceutils.Map(func(item apiclient.Project) AllProjectsDataSourceModelProjectsItem {
		var model AllProjectsDataSourceModelProjectsItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}, data))
	return
}

type AllProjectsDataSourceModelProjectsItem struct {
	Slug        supertypes.StringValue                                                             `tfsdk:"slug"`
	InternalId  supertypes.StringValue                                                             `tfsdk:"internal_id"`
	Name        supertypes.StringValue                                                             `tfsdk:"name"`
	Platform    supertypes.StringValue                                                             `tfsdk:"platform"`
	Color       supertypes.StringValue                                                             `tfsdk:"color"`
	DateCreated supertypes.StringValue                                                             `tfsdk:"date_created"`
	Features    supertypes.SetValueOf[string]                                                      `tfsdk:"features"`
	Teams       supertypes.SetNestedObjectValueOf[AllProjectsDataSourceModelProjectsItemTeamsItem] `tfsdk:"teams"`
}

func (m *AllProjectsDataSourceModelProjectsItem) Fill(ctx context.Context, data apiclient.Project) (diags diag.Diagnostics) {
	m.Slug = supertypes.NewStringValue(data.Slug)
	m.InternalId = supertypes.NewStringValue(data.Id)
	m.Name = supertypes.NewStringValue(data.Name)
	if v, err := data.Platform.Get(); err == nil {
		m.Platform = supertypes.NewStringValueOrNull(v)
	} else {
		m.Platform = supertypes.NewStringNull()
	}
	m.Color = supertypes.NewStringValue(data.Color)
	m.DateCreated = supertypes.NewStringValue(data.DateCreated.String())
	m.Features = supertypes.NewSetValueOfSlice(ctx, data.Features)
	m.Teams = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, sliceutils.Map(func(item apiclient.Team) AllProjectsDataSourceModelProjectsItemTeamsItem {
		var model AllProjectsDataSourceModelProjectsItemTeamsItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}, data.Teams))
	return
}

type AllProjectsDataSourceModelProjectsItemTeamsItem struct {
	InternalId supertypes.StringValue `tfsdk:"internal_id"`
	Name       supertypes.StringValue `tfsdk:"name"`
	Slug       supertypes.StringValue `tfsdk:"slug"`
}

func (m *AllProjectsDataSourceModelProjectsItemTeamsItem) Fill(ctx context.Context, data apiclient.Team) (diags diag.Diagnostics) {
	m.InternalId = supertypes.NewStringValue(data.Id)
	m.Name = supertypes.NewStringValue(data.Name)
	m.Slug = supertypes.NewStringValue(data.Slug)
	return
}
