// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/jianyuan/terraform-provider-sentry/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &AlertDataSource{}

func NewAlertDataSource() datasource.DataSource {
	return &AlertDataSource{}
}

type AlertDataSource struct {
	baseDataSource
}

func (d *AlertDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_alert"
}

func (d *AlertDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nRetrieve an Alert for a Monitor in an Organization.",
		Attributes: map[string]schema.Attribute{
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID of the alert.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of the alert.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the alert is enabled. Defaults to `true`.",
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of this alert.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"environment": schema.StringAttribute{
				MarkdownDescription: "Name of the environment for this alert.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"monitor_ids": schema.SetAttribute{
				MarkdownDescription: "The IDs of the monitors for this alert.",
				Computed:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
			"frequency_minutes": schema.Int64Attribute{
				MarkdownDescription: "How often the alert should fire in minutes.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"triggers_json": schema.StringAttribute{
				MarkdownDescription: "The triggers for this alert.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"action_filters_json": schema.StringAttribute{
				MarkdownDescription: "The filters to run before the action will fire and the action(s) to fire.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
		},
	}
}

func (d *AlertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data AlertDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.apiClient.GetOrganizationWorkflowWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type AlertDataSourceModel struct {
	Organization      supertypes.StringValue        `tfsdk:"organization"`
	Id                supertypes.StringValue        `tfsdk:"id"`
	Enabled           supertypes.BoolValue          `tfsdk:"enabled"`
	Name              supertypes.StringValue        `tfsdk:"name"`
	Environment       supertypes.StringValue        `tfsdk:"environment"`
	MonitorIds        supertypes.SetValueOf[string] `tfsdk:"monitor_ids"`
	FrequencyMinutes  supertypes.Int64Value         `tfsdk:"frequency_minutes"`
	TriggersJson      supertypes.StringValue        `tfsdk:"triggers_json"`
	ActionFiltersJson supertypes.StringValue        `tfsdk:"action_filters_json"`
}

func (m *AlertDataSourceModel) Fill(ctx context.Context, data apiclient.OrganizationWorkflow) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(data.Id)
	m.Enabled = supertypes.NewBoolValue(data.Enabled)
	m.Name = supertypes.NewStringValue(data.Name)
	m.Environment = supertypes.NewStringValue(data.Environment)
	m.MonitorIds = supertypes.NewSetValueOfSlice(ctx, data.DetectorIds)
	m.FrequencyMinutes = supertypes.NewInt64Value(data.Config.Frequency)

	if m, ok := any(m).(customFiller[apiclient.OrganizationWorkflow]); ok {
		diags.Append(m.fill(ctx, data)...)
	}
	return
}
