// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

var (
	AutoGeneratedResources   = []func() resource.Resource{}
	AutoGeneratedDataSources = []func() datasource.DataSource{
		NewAllProjectsDataSource,
		NewOrganizationDataSource,
		NewProjectDataSource,
	}
)
