// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

var (
	AutoGeneratedResources = []func() resource.Resource{
		NewAlertResource,
		NewCronMonitorResource,
		NewExternalUserResource,
		NewMetricMonitorResource,
		NewOrganizationResource,
		NewUptimeMonitorResource,
	}
	AutoGeneratedDataSources = []func() datasource.DataSource{
		NewAlertDataSource,
		NewAllProjectsDataSource,
		NewCronMonitorDataSource,
		NewMetricMonitorDataSource,
		NewOrganizationDataSource,
		NewProjectDataSource,
		NewProjectErrorMonitorDataSource,
		NewProjectIssueStreamMonitorDataSource,
		NewTeamDataSource,
		NewUptimeMonitorDataSource,
	}
)
