// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-sentry/internal/tfutils"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &OrganizationUserMappingResource{}
var _ resource.ResourceWithImportState = &OrganizationUserMappingResource{}

func NewOrganizationUserMappingResource() resource.Resource {
	return &OrganizationUserMappingResource{}
}

type OrganizationUserMappingResource struct {
	baseResource
}

func (r *OrganizationUserMappingResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_user_mapping"
}

func (r *OrganizationUserMappingResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a mapping between a Sentry organization member and an external identity\nprovider (for example GitHub, GitLab, Slack, or Jira Server).\n\nThese mappings link Sentry users to identities in an installed organization\nintegration so features such as issue assignment and commit attribution can\nresolve the correct person.\n\n~> **Note:** Sentry does not expose a read API for external user mappings. After\ncreate or import, Terraform keeps the mapping attributes in state and does not\nrefresh them from the API on subsequent plans.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The resource ID in the form `organization/internal_id`.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "The slug of the organization the mapping belongs to.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"internal_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this external user mapping (generated by Sentry).",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"user_id": schema.Int64Attribute{
				MarkdownDescription: "The Sentry user ID to map.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"external_name": schema.StringAttribute{
				MarkdownDescription: "The display name of the identity in the external provider.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"external_provider": schema.StringAttribute{
				MarkdownDescription: "The external identity provider. Valid values are `github`, `github_enterprise`, `jira_server`, `slack`, `gitlab`, `msteams`, and `custom_scm`.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.OneOf("github", "github_enterprise", "jira_server", "slack", "gitlab", "msteams", "custom_scm"),
				},
			},
			"integration_id": schema.Int64Attribute{
				MarkdownDescription: "The ID of the organization integration for the external provider.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"external_id": schema.StringAttribute{
				MarkdownDescription: "The actor ID in the external provider (for example a GitLab or GitHub user ID).",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
		},
	}
}

func (r *OrganizationUserMappingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data OrganizationUserMappingResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	} else if body == nil {
		resp.Diagnostics.AddError("Provider Error", "getCreateJSONRequestBody returned a nil body")
		return
	}

	httpResp, err := r.apiClient.CreateOrganizationExternalUserWithResponse(ctx, data.Organization.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON201)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationUserMappingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data OrganizationUserMappingResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(r.read(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationUserMappingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data OrganizationUserMappingResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.UpdateOrganizationExternalUserWithResponse(ctx, data.Organization.ValueString(), data.InternalId.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationUserMappingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data OrganizationUserMappingResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.DeleteOrganizationExternalUserWithResponse(ctx, data.Organization.ValueString(), data.InternalId.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

func (r *OrganizationUserMappingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	organization, internalId, err := tfutils.SplitTwoPartId(req.ID, "organization", "internal_id")
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Error parsing ID: %s", err.Error()))
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("organization"), organization)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("internal_id"), internalId)...)
}

type OrganizationUserMappingResourceModel struct {
	Id               supertypes.StringValue `tfsdk:"id"`
	Organization     supertypes.StringValue `tfsdk:"organization"`
	InternalId       supertypes.StringValue `tfsdk:"internal_id"`
	UserId           supertypes.Int64Value  `tfsdk:"user_id"`
	ExternalName     supertypes.StringValue `tfsdk:"external_name"`
	ExternalProvider supertypes.StringValue `tfsdk:"external_provider"`
	IntegrationId    supertypes.Int64Value  `tfsdk:"integration_id"`
	ExternalId       supertypes.StringValue `tfsdk:"external_id"`
}
