// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-sentry/internal/sentrydata"
	"github.com/jianyuan/terraform-provider-sentry/internal/tfutils"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	fstringvalidator "github.com/orange-cloudavenue/terraform-plugin-framework-validators/stringvalidator"
)

var _ resource.Resource = &AlertResource{}
var _ resource.ResourceWithImportState = &AlertResource{}

func NewAlertResource() resource.Resource {
	return &AlertResource{}
}

type AlertResource struct {
	baseResource
}

func (r *AlertResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_alert"
}

func (r *AlertResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nCreate an Alert for a Monitor in an Organization. Monitors must be created separately using the [`sentry_cron_monitor`](cron_monitor.md), [`sentry_metric_monitor`](metric_monitor.md), or [`sentry_uptime_monitor`](uptime_monitor.md) resources.\n\nAdditionally, [default monitors](https://docs.sentry.io/product/new-monitors-and-alerts/monitors/#default-monitors) are automatically created for each project. Use the [`sentry_monitor`](../data-sources/monitor.md) data source to retrieve them.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this alert.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID to create the alert for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the alert is enabled. Defaults to `true`.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of this alert.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"environment": schema.StringAttribute{
				MarkdownDescription: "Name of the environment to create alerts in.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"monitor_ids": schema.SetAttribute{
				MarkdownDescription: "The IDs of the monitors to create alerts for.",
				Required:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
			"frequency_minutes": schema.Int64Attribute{
				MarkdownDescription: "How often the alert should fire in minutes.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"trigger_conditions": schema.ListNestedAttribute{
				MarkdownDescription: "The conditions on which the alert will trigger.",
				Required:            true,
				CustomType:          supertypes.NewListNestedObjectTypeOf[AlertResourceModelTriggerConditionsItem](ctx),
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"first_seen_event": schema.SingleNestedAttribute{
							MarkdownDescription: "A new issue is created.",
							Optional:            true,
							CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelTriggerConditionsItemFirstSeenEvent](ctx),
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("issue_resolved_trigger"), path.MatchRelative().AtParent().AtName("reappeared_event"), path.MatchRelative().AtParent().AtName("regression_event")),
							},
							Attributes: map[string]schema.Attribute{},
						},
						"issue_resolved_trigger": schema.SingleNestedAttribute{
							MarkdownDescription: "An issue is resolved.",
							Optional:            true,
							CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelTriggerConditionsItemIssueResolvedTrigger](ctx),
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("first_seen_event"), path.MatchRelative().AtParent().AtName("reappeared_event"), path.MatchRelative().AtParent().AtName("regression_event")),
							},
							Attributes: map[string]schema.Attribute{},
						},
						"reappeared_event": schema.SingleNestedAttribute{
							MarkdownDescription: "An issue escalates.",
							Optional:            true,
							CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelTriggerConditionsItemReappearedEvent](ctx),
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("first_seen_event"), path.MatchRelative().AtParent().AtName("issue_resolved_trigger"), path.MatchRelative().AtParent().AtName("regression_event")),
							},
							Attributes: map[string]schema.Attribute{},
						},
						"regression_event": schema.SingleNestedAttribute{
							MarkdownDescription: "A resolved issue becomes unresolved.",
							Optional:            true,
							CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelTriggerConditionsItemRegressionEvent](ctx),
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("first_seen_event"), path.MatchRelative().AtParent().AtName("issue_resolved_trigger"), path.MatchRelative().AtParent().AtName("reappeared_event")),
							},
							Attributes: map[string]schema.Attribute{},
						},
					},
				},
			},
			"action_filters": schema.ListNestedAttribute{
				MarkdownDescription: "The filters to run before the action will fire and the action(s) to fire.",
				Required:            true,
				CustomType:          supertypes.NewListNestedObjectTypeOf[AlertResourceModelActionFiltersItem](ctx),
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"logic_type": tfutils.WithEnumStringAttribute(
							schema.StringAttribute{
								MarkdownDescription: "The logic to apply to the conditions. `any` will evaluate all conditions, and return true if any of those are met. `any-short` will stop evaluating conditions as soon as one is met. `all` will evaluate all conditions, and return true if all of those are met. `none` will return true if none of the conditions are met, will return false immediately if any are met.",
								Required:            true,
								CustomType:          supertypes.StringType{},
							},
							sentrydata.DataConditionGroupTypes,
						),
						"conditions": schema.ListNestedAttribute{
							MarkdownDescription: "The conditions to evaluate.",
							Optional:            true,
							Computed:            true,
							CustomType:          supertypes.NewListNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItem](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"age_comparison": schema.SingleNestedAttribute{
										MarkdownDescription: "Issue age.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemAgeComparison](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"time": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The unit of time for the age comparison.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												[]string{"minute", "hour", "day", "week"},
											),
											"value": schema.Int64Attribute{
												MarkdownDescription: "The value of the age comparison.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
											"comparison_type": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The type of comparison to perform.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												[]string{"older", "newer"},
											),
										},
									},
									"assigned_to": schema.SingleNestedAttribute{
										MarkdownDescription: "Issue assignment.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemAssignedTo](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"target_type": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "Who the issue is assigned to.",
													Optional:            true,
													CustomType:          supertypes.StringType{},
												},
												[]string{"Unassigned", "Member", "Team"},
											),
											"target_id": schema.StringAttribute{
												MarkdownDescription: "The internal ID of the user or team. Only required if the target type is `Member` or `Team`.",
												Optional:            true,
												CustomType:          supertypes.StringType{},
												Validators: []validator.String{
													fstringvalidator.RequireIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("target_type"), []attr.Value{supertypes.NewStringValue("Member"), supertypes.NewStringValue("Team")}),
													fstringvalidator.NullIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("target_type"), []attr.Value{supertypes.NewStringValue("Unassigned")}),
												},
											},
										},
									},
									"issue_category": schema.SingleNestedAttribute{
										MarkdownDescription: "Issue category.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemIssueCategory](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "The issue category to filter to.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
											},
										},
									},
									"issue_occurrences": schema.SingleNestedAttribute{
										MarkdownDescription: "Issue frequency.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemIssueOccurrences](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "A positive integer representing how many times the issue has to happen before the alert will fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
										},
									},
									"issue_priority_deescalating": schema.SingleNestedAttribute{
										MarkdownDescription: "De-escalation.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemIssuePriorityDeescalating](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{},
									},
									"issue_priority_greater_or_equal": schema.SingleNestedAttribute{
										MarkdownDescription: "Issue priority.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemIssuePriorityGreaterOrEqual](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"comparison": schema.Int64Attribute{
												MarkdownDescription: "he priority the issue must be for the alert to fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
											},
										},
									},
									"event_unique_user_frequency_count": schema.SingleNestedAttribute{
										MarkdownDescription: "Number of users affected.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemEventUniqueUserFrequencyCount](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "A positive integer representing the number of users that must be affected before the alert will fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
											"filters": schema.ListNestedAttribute{
												MarkdownDescription: "A list of additional sub-filters to evaluate before the alert will fire.",
												Optional:            true,
												Computed:            true,
												CustomType:          supertypes.NewListNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemEventUniqueUserFrequencyCountFiltersItem](ctx),
												NestedObject: schema.NestedAttributeObject{
													Attributes: map[string]schema.Attribute{
														"key": schema.StringAttribute{
															MarkdownDescription: "The key of the filter. Conflicts with `attribute`.",
															Optional:            true,
															CustomType:          supertypes.StringType{},
															Validators: []validator.String{
																stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("attribute")),
															},
														},
														"attribute": schema.StringAttribute{
															MarkdownDescription: "The attribute of the filter. Conflicts with `key`.",
															Optional:            true,
															CustomType:          supertypes.StringType{},
															Validators: []validator.String{
																stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("key")),
															},
														},
														"match": schema.StringAttribute{
															MarkdownDescription: "The match type of the filter.",
															Optional:            true,
															CustomType:          supertypes.StringType{},
														},
														"value": schema.StringAttribute{
															MarkdownDescription: "The value of the filter.",
															Optional:            true,
															CustomType:          supertypes.StringType{},
														},
													},
												},
											},
											"interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period in which to evaluate the value. e.g. Number of users affected by an issue is more than `value` in `interval`.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
										},
									},
									"event_frequency_count": schema.SingleNestedAttribute{
										MarkdownDescription: "Number of events.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemEventFrequencyCount](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "A positive integer representing the number of events in an issue that must come in before the alert will fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
											"interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period in which to evaluate the value. e.g. Number of events in an issue is more than `value` in `interval`.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
										},
									},
									"event_frequency_percent": schema.SingleNestedAttribute{
										MarkdownDescription: "Percent of events.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemEventFrequencyPercent](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "A positive integer representing the number of events in an issue that must come in before the alert will fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
											"interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period in which to evaluate the value. e.g. Number of events in an issue is `comparisonInterval` percent higher `value` compared to `interval`.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
											"comparison_interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period to compare against.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
										},
									},
									"percent_sessions_count": schema.SingleNestedAttribute{
										MarkdownDescription: "Percentage of sessions affected count.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemPercentSessionsCount](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "A positive integer representing the number of events in an issue that must come in before the alert will fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
											"interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period in which to evaluate the value. e.g. Percentage of sessions affected by an issue is more than `value` in `interval`.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
										},
									},
									"percent_sessions_percent": schema.SingleNestedAttribute{
										MarkdownDescription: "Percentage of sessions affected percent.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemPercentSessionsPercent](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"value": schema.Int64Attribute{
												MarkdownDescription: "A positive integer representing the number of events in an issue that must come in before the alert will fire.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
												Validators: []validator.Int64{
													int64validator.AtLeast(1),
												},
											},
											"interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period in which to evaluate the value. e.g. Percentage of sessions affected by an issue is `comparisonInterval` percent higher `value` compared to `interval`.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
											"comparison_interval": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The time period to compare against.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												sentrydata.EventFrequencyStandardIntervals,
											),
										},
									},
									"event_attribute": schema.SingleNestedAttribute{
										MarkdownDescription: "The event's `attribute` value `match` `value`.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemEventAttribute](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"attribute": schema.StringAttribute{
												MarkdownDescription: "The attribute to evaluate.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"match": schema.StringAttribute{
												MarkdownDescription: "The match type.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"value": schema.StringAttribute{
												MarkdownDescription: "The value to compare against.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"tagged_event": schema.SingleNestedAttribute{
										MarkdownDescription: "The event's tags `key` match `value`.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemTaggedEvent](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"key": schema.StringAttribute{
												MarkdownDescription: "The tag value.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"match": schema.StringAttribute{
												MarkdownDescription: "The comparison operator.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"value": schema.StringAttribute{
												MarkdownDescription: "A string. Not required when match is `is` or `ns`.",
												Optional:            true,
												CustomType:          supertypes.StringType{},
												Validators: []validator.String{
													fstringvalidator.NullIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("match"), []attr.Value{supertypes.NewStringValue("is"), supertypes.NewStringValue("ns")}),
												},
											},
										},
									},
									"latest_release": schema.SingleNestedAttribute{
										MarkdownDescription: "The event is from the latest release.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemLatestRelease](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_adopted_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{},
									},
									"latest_adopted_release": schema.SingleNestedAttribute{
										MarkdownDescription: "The `release_age_type` adopted release associated with the event's issue is `age_comparison` than the latest adopted release in `environment`.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemLatestAdoptedRelease](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("level")),
										},
										Attributes: map[string]schema.Attribute{
											"environment": schema.StringAttribute{
												MarkdownDescription: "The environment to compare against.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"age_comparison": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The age comparison to use.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												[]string{"older", "newer"},
											),
											"release_age_type": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The release age type to use.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												[]string{"oldest", "newest"},
											),
										},
									},
									"level": schema.SingleNestedAttribute{
										MarkdownDescription: "The event's level match `level`.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemConditionsItemLevel](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("age_comparison"), path.MatchRelative().AtParent().AtName("assigned_to"), path.MatchRelative().AtParent().AtName("issue_category"), path.MatchRelative().AtParent().AtName("issue_occurrences"), path.MatchRelative().AtParent().AtName("issue_priority_deescalating"), path.MatchRelative().AtParent().AtName("issue_priority_greater_or_equal"), path.MatchRelative().AtParent().AtName("event_unique_user_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_count"), path.MatchRelative().AtParent().AtName("event_frequency_percent"), path.MatchRelative().AtParent().AtName("percent_sessions_count"), path.MatchRelative().AtParent().AtName("percent_sessions_percent"), path.MatchRelative().AtParent().AtName("event_attribute"), path.MatchRelative().AtParent().AtName("tagged_event"), path.MatchRelative().AtParent().AtName("latest_release"), path.MatchRelative().AtParent().AtName("latest_adopted_release")),
										},
										Attributes: map[string]schema.Attribute{
											"match": schema.StringAttribute{
												MarkdownDescription: "The comparison operator.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"level": schema.Int64Attribute{
												MarkdownDescription: "The level to compare against.",
												Required:            true,
												CustomType:          supertypes.Int64Type{},
											},
										},
									},
								},
							},
						},
						"actions": schema.ListNestedAttribute{
							MarkdownDescription: "The actions to perform.",
							Required:            true,
							CustomType:          supertypes.NewListNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItem](ctx),
							Validators: []validator.List{
								listvalidator.SizeAtLeast(1),
							},
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"email": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on Preferred Channel.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemEmail](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"target_type": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The type of recipient to notify.",
													Required:            true,
													CustomType:          supertypes.StringType{},
												},
												[]string{"issue_owners", "team", "user"},
											),
											"target_id": schema.StringAttribute{
												MarkdownDescription: "The internal ID of the user or team. Only required if the target type is `team` or `user`.",
												Optional:            true,
												CustomType:          supertypes.StringType{},
												Validators: []validator.String{
													fstringvalidator.RequireIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("target_type"), []attr.Value{supertypes.NewStringValue("team"), supertypes.NewStringValue("user")}),
													fstringvalidator.NullIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("target_type"), []attr.Value{supertypes.NewStringValue("issue_owners")}),
												},
											},
											"fallthrough_type": tfutils.WithEnumStringAttribute(
												schema.StringAttribute{
													MarkdownDescription: "The type of fallthrough to apply when choosing to notify issue owners. Only required if the target type is `issue_owners`.",
													Optional:            true,
													CustomType:          supertypes.StringType{},
													Validators: []validator.String{
														fstringvalidator.RequireIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("target_type"), []attr.Value{supertypes.NewStringValue("issue_owners")}),
														fstringvalidator.NullIfAttributeIsOneOf(path.MatchRelative().AtParent().AtName("target_type"), []attr.Value{supertypes.NewStringValue("team"), supertypes.NewStringValue("user")}),
													},
												},
												[]string{"AllMembers", "ActiveMembers", "NoOne"},
											),
										},
									},
									"plugin": schema.SingleNestedAttribute{
										MarkdownDescription: "Send a notification to all legacy integrations (plugins).",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemPlugin](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{},
									},
									"slack": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on Slack.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemSlack](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Slack integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"channel_name": schema.StringAttribute{
												MarkdownDescription: "The name of the Slack channel to send the notification to (e.g., #critical, Jane Schmidt).",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"channel_id": schema.StringAttribute{
												MarkdownDescription: "The Slack channel ID to send the notification to. This is an optional field that can be used to avoid rate-limiting.",
												Optional:            true,
												Computed:            true,
												CustomType:          supertypes.StringType{},
											},
											"tags": schema.StringAttribute{
												MarkdownDescription: "A list of tags to show in the notification.",
												Optional:            true,
												Computed:            true,
												CustomType:          supertypes.StringType{},
											},
											"notes": schema.StringAttribute{
												MarkdownDescription: "Text to show alongside the notification. To @ a user, include their user id like `@<USER_ID>`. To include a clickable link, format the link and title like `<http://example.com|Click Here>`.",
												Optional:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"pagerduty": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on PagerDuty.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemPagerduty](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the PagerDuty integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"service_name": schema.StringAttribute{
												MarkdownDescription: "The name of the service to create the ticket in.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"service_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the PagerDuty service.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"severity": schema.StringAttribute{
												MarkdownDescription: "The PagerDuty severity level for the notification.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"discord": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on Discord.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemDiscord](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Discord integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"channel_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Discord channel to send the notification to.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"tags": schema.StringAttribute{
												MarkdownDescription: "A list of tags to show in the notification.",
												Optional:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"msteams": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on Microsoft Teams.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemMsteams](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Microsoft Teams integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"team_id": schema.StringAttribute{
												MarkdownDescription: "The integration ID associated with the Microsoft Teams team.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"channel_name": schema.StringAttribute{
												MarkdownDescription: "The name of the Microsoft Teams channel to send the notification to.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"opsgenie": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on OpsGenie.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemOpsgenie](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the OpsGenie integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"team_name": schema.StringAttribute{
												MarkdownDescription: "The name of the Opsgenie team.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"team_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Opsgenie team to send the notification to.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"priority": schema.StringAttribute{
												MarkdownDescription: "The priority level for the notification.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"vsts": schema.SingleNestedAttribute{
										MarkdownDescription: "Notify on Azure DevOps.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemVsts](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the OpsGenie integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"project": schema.StringAttribute{
												MarkdownDescription: "The ID of the Azure DevOps project.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"work_item_type": schema.StringAttribute{
												MarkdownDescription: "The type of work item to create.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"jira": schema.SingleNestedAttribute{
										MarkdownDescription: "Create a Jira ticket.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemJira](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Jira integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"project": schema.StringAttribute{
												MarkdownDescription: "The ID of the Jira project.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"issue_type": schema.StringAttribute{
												MarkdownDescription: "The ID of the type of issue that the ticket should be created as.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"jira_server": schema.SingleNestedAttribute{
										MarkdownDescription: "Create a Jira Server ticket.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemJiraServer](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("github"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the Jira Server integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"project": schema.StringAttribute{
												MarkdownDescription: "The ID of the Jira project.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"issue_type": schema.StringAttribute{
												MarkdownDescription: "The ID of the type of issue that the ticket should be created as.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
										},
									},
									"github": schema.SingleNestedAttribute{
										MarkdownDescription: "Create a GitHub issue.",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemGithub](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("sentry_app")),
										},
										Attributes: map[string]schema.Attribute{
											"integration_id": schema.StringAttribute{
												MarkdownDescription: "The ID of the GitHub integration.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"repo": schema.StringAttribute{
												MarkdownDescription: "The name of the repository to create the issue in.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"assignee": schema.StringAttribute{
												MarkdownDescription: "The GitHub user to assign the issue to.",
												Optional:            true,
												CustomType:          supertypes.StringType{},
											},
											"labels": schema.SetAttribute{
												MarkdownDescription: "A list of labels to assign to the issue.",
												Optional:            true,
												CustomType:          supertypes.NewSetTypeOf[string](ctx),
											},
										},
									},
									"sentry_app": schema.SingleNestedAttribute{
										MarkdownDescription: "Trigger an action in a Sentry App (e.g. Rootly).",
										Optional:            true,
										CustomType:          supertypes.NewSingleNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemSentryApp](ctx),
										Validators: []validator.Object{
											objectvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("email"), path.MatchRelative().AtParent().AtName("plugin"), path.MatchRelative().AtParent().AtName("slack"), path.MatchRelative().AtParent().AtName("pagerduty"), path.MatchRelative().AtParent().AtName("discord"), path.MatchRelative().AtParent().AtName("msteams"), path.MatchRelative().AtParent().AtName("opsgenie"), path.MatchRelative().AtParent().AtName("vsts"), path.MatchRelative().AtParent().AtName("jira"), path.MatchRelative().AtParent().AtName("jira_server"), path.MatchRelative().AtParent().AtName("github")),
										},
										Attributes: map[string]schema.Attribute{
											"sentry_app_id": schema.StringAttribute{
												MarkdownDescription: "The numeric Sentry App ID. Use `tostring(data.sentry_app_installation.<name>.sentry_app_id)` to source this value.",
												Required:            true,
												CustomType:          supertypes.StringType{},
											},
											"settings": schema.ListNestedAttribute{
												MarkdownDescription: "Key-value settings passed to the Sentry App action. Specifying `label` preserves the human-readable display name in the Sentry UI for async select fields whose options are paginated by the third-party app.",
												Optional:            true,
												CustomType:          supertypes.NewListNestedObjectTypeOf[AlertResourceModelActionFiltersItemActionsItemSentryAppSettingsItem](ctx),
												NestedObject: schema.NestedAttributeObject{
													Attributes: map[string]schema.Attribute{
														"name": schema.StringAttribute{
															MarkdownDescription: "The name of the setting field.",
															Required:            true,
															CustomType:          supertypes.StringType{},
														},
														"value": schema.StringAttribute{
															MarkdownDescription: "The value of the setting field.",
															Required:            true,
															CustomType:          supertypes.StringType{},
														},
														"label": schema.StringAttribute{
															MarkdownDescription: "The human-readable display label for the value. Required for async select fields whose option list is paginated by the third-party app — without it the field may appear blank under certain conditions in the Sentry UI after apply.",
															Optional:            true,
															Computed:            true,
															CustomType:          supertypes.StringType{},
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *AlertResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AlertResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	} else if body == nil {
		resp.Diagnostics.AddError("Provider Error", "getCreateJSONRequestBody returned a nil body")
		return
	}

	httpResp, err := r.apiClient.CreateOrganizationWorkflowWithResponse(ctx, data.Organization.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON201)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AlertResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AlertResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.GetOrganizationWorkflowWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	responseData := httpResp.JSON200

	if responseData == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AlertResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data AlertResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.UpdateOrganizationWorkflowWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AlertResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AlertResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.DeleteOrganizationWorkflowWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

func (r *AlertResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	organization, id, err := tfutils.SplitTwoPartId(req.ID, "organization", "id")
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Error parsing ID: %s", err.Error()))
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("organization"), organization)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}

type AlertResourceModel struct {
	Id                supertypes.StringValue                                                      `tfsdk:"id"`
	Organization      supertypes.StringValue                                                      `tfsdk:"organization"`
	Enabled           supertypes.BoolValue                                                        `tfsdk:"enabled"`
	Name              supertypes.StringValue                                                      `tfsdk:"name"`
	Environment       supertypes.StringValue                                                      `tfsdk:"environment"`
	MonitorIds        supertypes.SetValueOf[string]                                               `tfsdk:"monitor_ids"`
	FrequencyMinutes  supertypes.Int64Value                                                       `tfsdk:"frequency_minutes"`
	TriggerConditions supertypes.ListNestedObjectValueOf[AlertResourceModelTriggerConditionsItem] `tfsdk:"trigger_conditions"`
	ActionFilters     supertypes.ListNestedObjectValueOf[AlertResourceModelActionFiltersItem]     `tfsdk:"action_filters"`
}

type AlertResourceModelTriggerConditionsItem struct {
	FirstSeenEvent       supertypes.SingleNestedObjectValueOf[AlertResourceModelTriggerConditionsItemFirstSeenEvent]       `tfsdk:"first_seen_event"`
	IssueResolvedTrigger supertypes.SingleNestedObjectValueOf[AlertResourceModelTriggerConditionsItemIssueResolvedTrigger] `tfsdk:"issue_resolved_trigger"`
	ReappearedEvent      supertypes.SingleNestedObjectValueOf[AlertResourceModelTriggerConditionsItemReappearedEvent]      `tfsdk:"reappeared_event"`
	RegressionEvent      supertypes.SingleNestedObjectValueOf[AlertResourceModelTriggerConditionsItemRegressionEvent]      `tfsdk:"regression_event"`
}

type AlertResourceModelTriggerConditionsItemFirstSeenEvent struct {
}

type AlertResourceModelTriggerConditionsItemIssueResolvedTrigger struct {
}

type AlertResourceModelTriggerConditionsItemReappearedEvent struct {
}

type AlertResourceModelTriggerConditionsItemRegressionEvent struct {
}

type AlertResourceModelActionFiltersItem struct {
	LogicType  supertypes.StringValue                                                                `tfsdk:"logic_type"`
	Conditions supertypes.ListNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItem] `tfsdk:"conditions"`
	Actions    supertypes.ListNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItem]    `tfsdk:"actions"`
}

type AlertResourceModelActionFiltersItemConditionsItem struct {
	AgeComparison                 supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemAgeComparison]                 `tfsdk:"age_comparison"`
	AssignedTo                    supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemAssignedTo]                    `tfsdk:"assigned_to"`
	IssueCategory                 supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemIssueCategory]                 `tfsdk:"issue_category"`
	IssueOccurrences              supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemIssueOccurrences]              `tfsdk:"issue_occurrences"`
	IssuePriorityDeescalating     supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemIssuePriorityDeescalating]     `tfsdk:"issue_priority_deescalating"`
	IssuePriorityGreaterOrEqual   supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemIssuePriorityGreaterOrEqual]   `tfsdk:"issue_priority_greater_or_equal"`
	EventUniqueUserFrequencyCount supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemEventUniqueUserFrequencyCount] `tfsdk:"event_unique_user_frequency_count"`
	EventFrequencyCount           supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemEventFrequencyCount]           `tfsdk:"event_frequency_count"`
	EventFrequencyPercent         supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemEventFrequencyPercent]         `tfsdk:"event_frequency_percent"`
	PercentSessionsCount          supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemPercentSessionsCount]          `tfsdk:"percent_sessions_count"`
	PercentSessionsPercent        supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemPercentSessionsPercent]        `tfsdk:"percent_sessions_percent"`
	EventAttribute                supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemEventAttribute]                `tfsdk:"event_attribute"`
	TaggedEvent                   supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemTaggedEvent]                   `tfsdk:"tagged_event"`
	LatestRelease                 supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemLatestRelease]                 `tfsdk:"latest_release"`
	LatestAdoptedRelease          supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemLatestAdoptedRelease]          `tfsdk:"latest_adopted_release"`
	Level                         supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemLevel]                         `tfsdk:"level"`
}

type AlertResourceModelActionFiltersItemConditionsItemAgeComparison struct {
	Time           supertypes.StringValue `tfsdk:"time"`
	Value          supertypes.Int64Value  `tfsdk:"value"`
	ComparisonType supertypes.StringValue `tfsdk:"comparison_type"`
}

type AlertResourceModelActionFiltersItemConditionsItemAssignedTo struct {
	TargetType supertypes.StringValue `tfsdk:"target_type"`
	TargetId   supertypes.StringValue `tfsdk:"target_id"`
}

type AlertResourceModelActionFiltersItemConditionsItemIssueCategory struct {
	Value supertypes.Int64Value `tfsdk:"value"`
}

type AlertResourceModelActionFiltersItemConditionsItemIssueOccurrences struct {
	Value supertypes.Int64Value `tfsdk:"value"`
}

type AlertResourceModelActionFiltersItemConditionsItemIssuePriorityDeescalating struct {
}

type AlertResourceModelActionFiltersItemConditionsItemIssuePriorityGreaterOrEqual struct {
	Comparison supertypes.Int64Value `tfsdk:"comparison"`
}

type AlertResourceModelActionFiltersItemConditionsItemEventUniqueUserFrequencyCount struct {
	Value    supertypes.Int64Value                                                                                                         `tfsdk:"value"`
	Filters  supertypes.ListNestedObjectValueOf[AlertResourceModelActionFiltersItemConditionsItemEventUniqueUserFrequencyCountFiltersItem] `tfsdk:"filters"`
	Interval supertypes.StringValue                                                                                                        `tfsdk:"interval"`
}

type AlertResourceModelActionFiltersItemConditionsItemEventUniqueUserFrequencyCountFiltersItem struct {
	Key       supertypes.StringValue `tfsdk:"key"`
	Attribute supertypes.StringValue `tfsdk:"attribute"`
	Match     supertypes.StringValue `tfsdk:"match"`
	Value     supertypes.StringValue `tfsdk:"value"`
}

type AlertResourceModelActionFiltersItemConditionsItemEventFrequencyCount struct {
	Value    supertypes.Int64Value  `tfsdk:"value"`
	Interval supertypes.StringValue `tfsdk:"interval"`
}

type AlertResourceModelActionFiltersItemConditionsItemEventFrequencyPercent struct {
	Value              supertypes.Int64Value  `tfsdk:"value"`
	Interval           supertypes.StringValue `tfsdk:"interval"`
	ComparisonInterval supertypes.StringValue `tfsdk:"comparison_interval"`
}

type AlertResourceModelActionFiltersItemConditionsItemPercentSessionsCount struct {
	Value    supertypes.Int64Value  `tfsdk:"value"`
	Interval supertypes.StringValue `tfsdk:"interval"`
}

type AlertResourceModelActionFiltersItemConditionsItemPercentSessionsPercent struct {
	Value              supertypes.Int64Value  `tfsdk:"value"`
	Interval           supertypes.StringValue `tfsdk:"interval"`
	ComparisonInterval supertypes.StringValue `tfsdk:"comparison_interval"`
}

type AlertResourceModelActionFiltersItemConditionsItemEventAttribute struct {
	Attribute supertypes.StringValue `tfsdk:"attribute"`
	Match     supertypes.StringValue `tfsdk:"match"`
	Value     supertypes.StringValue `tfsdk:"value"`
}

type AlertResourceModelActionFiltersItemConditionsItemTaggedEvent struct {
	Key   supertypes.StringValue `tfsdk:"key"`
	Match supertypes.StringValue `tfsdk:"match"`
	Value supertypes.StringValue `tfsdk:"value"`
}

type AlertResourceModelActionFiltersItemConditionsItemLatestRelease struct {
}

type AlertResourceModelActionFiltersItemConditionsItemLatestAdoptedRelease struct {
	Environment    supertypes.StringValue `tfsdk:"environment"`
	AgeComparison  supertypes.StringValue `tfsdk:"age_comparison"`
	ReleaseAgeType supertypes.StringValue `tfsdk:"release_age_type"`
}

type AlertResourceModelActionFiltersItemConditionsItemLevel struct {
	Match supertypes.StringValue `tfsdk:"match"`
	Level supertypes.Int64Value  `tfsdk:"level"`
}

type AlertResourceModelActionFiltersItemActionsItem struct {
	Email      supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemEmail]      `tfsdk:"email"`
	Plugin     supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemPlugin]     `tfsdk:"plugin"`
	Slack      supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemSlack]      `tfsdk:"slack"`
	Pagerduty  supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemPagerduty]  `tfsdk:"pagerduty"`
	Discord    supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemDiscord]    `tfsdk:"discord"`
	Msteams    supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemMsteams]    `tfsdk:"msteams"`
	Opsgenie   supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemOpsgenie]   `tfsdk:"opsgenie"`
	Vsts       supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemVsts]       `tfsdk:"vsts"`
	Jira       supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemJira]       `tfsdk:"jira"`
	JiraServer supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemJiraServer] `tfsdk:"jira_server"`
	Github     supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemGithub]     `tfsdk:"github"`
	SentryApp  supertypes.SingleNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemSentryApp]  `tfsdk:"sentry_app"`
}

type AlertResourceModelActionFiltersItemActionsItemEmail struct {
	TargetType      supertypes.StringValue `tfsdk:"target_type"`
	TargetId        supertypes.StringValue `tfsdk:"target_id"`
	FallthroughType supertypes.StringValue `tfsdk:"fallthrough_type"`
}

type AlertResourceModelActionFiltersItemActionsItemPlugin struct {
}

type AlertResourceModelActionFiltersItemActionsItemSlack struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	ChannelName   supertypes.StringValue `tfsdk:"channel_name"`
	ChannelId     supertypes.StringValue `tfsdk:"channel_id"`
	Tags          supertypes.StringValue `tfsdk:"tags"`
	Notes         supertypes.StringValue `tfsdk:"notes"`
}

type AlertResourceModelActionFiltersItemActionsItemPagerduty struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	ServiceName   supertypes.StringValue `tfsdk:"service_name"`
	ServiceId     supertypes.StringValue `tfsdk:"service_id"`
	Severity      supertypes.StringValue `tfsdk:"severity"`
}

type AlertResourceModelActionFiltersItemActionsItemDiscord struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	ChannelId     supertypes.StringValue `tfsdk:"channel_id"`
	Tags          supertypes.StringValue `tfsdk:"tags"`
}

type AlertResourceModelActionFiltersItemActionsItemMsteams struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	TeamId        supertypes.StringValue `tfsdk:"team_id"`
	ChannelName   supertypes.StringValue `tfsdk:"channel_name"`
}

type AlertResourceModelActionFiltersItemActionsItemOpsgenie struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	TeamName      supertypes.StringValue `tfsdk:"team_name"`
	TeamId        supertypes.StringValue `tfsdk:"team_id"`
	Priority      supertypes.StringValue `tfsdk:"priority"`
}

type AlertResourceModelActionFiltersItemActionsItemVsts struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	Project       supertypes.StringValue `tfsdk:"project"`
	WorkItemType  supertypes.StringValue `tfsdk:"work_item_type"`
}

type AlertResourceModelActionFiltersItemActionsItemJira struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	Project       supertypes.StringValue `tfsdk:"project"`
	IssueType     supertypes.StringValue `tfsdk:"issue_type"`
}

type AlertResourceModelActionFiltersItemActionsItemJiraServer struct {
	IntegrationId supertypes.StringValue `tfsdk:"integration_id"`
	Project       supertypes.StringValue `tfsdk:"project"`
	IssueType     supertypes.StringValue `tfsdk:"issue_type"`
}

type AlertResourceModelActionFiltersItemActionsItemGithub struct {
	IntegrationId supertypes.StringValue        `tfsdk:"integration_id"`
	Repo          supertypes.StringValue        `tfsdk:"repo"`
	Assignee      supertypes.StringValue        `tfsdk:"assignee"`
	Labels        supertypes.SetValueOf[string] `tfsdk:"labels"`
}

type AlertResourceModelActionFiltersItemActionsItemSentryApp struct {
	SentryAppId supertypes.StringValue                                                                                  `tfsdk:"sentry_app_id"`
	Settings    supertypes.ListNestedObjectValueOf[AlertResourceModelActionFiltersItemActionsItemSentryAppSettingsItem] `tfsdk:"settings"`
}

type AlertResourceModelActionFiltersItemActionsItemSentryAppSettingsItem struct {
	Name  supertypes.StringValue `tfsdk:"name"`
	Value supertypes.StringValue `tfsdk:"value"`
	Label supertypes.StringValue `tfsdk:"label"`
}
