// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-sentry/internal/sentrydata"
	"github.com/jianyuan/terraform-provider-sentry/internal/tfutils"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &MetricMonitorResource{}

func NewMetricMonitorResource() resource.Resource {
	return &MetricMonitorResource{}
}

type MetricMonitorResource struct {
	baseResource
}

func (r *MetricMonitorResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_metric_monitor"
}

func (r *MetricMonitorResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Create a Metric Monitor for a Project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID to create the monitor for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "The project slug or internal ID to create the monitor for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled. Defaults to true.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of this monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "A description of the monitor. Will be used in the resulting issue.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
			},
			"default_assignee": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Optional:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MetricMonitorResourceModelDefaultAssignee](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user ID to assign new issues to. Conflicts with `team_id`.",
						Optional:            true,
						CustomType:          supertypes.StringType{},
						Validators: []validator.String{
							stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("team_id")),
						},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to. Conflicts with `user_id`.",
						Optional:            true,
						CustomType:          supertypes.StringType{},
						Validators: []validator.String{
							stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("user_id")),
						},
					},
				},
			},
			"aggregate": schema.StringAttribute{
				MarkdownDescription: "TODO",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"dataset": tfutils.WithEnumStringAttribute(
				schema.StringAttribute{
					MarkdownDescription: "TODO",
					Required:            true,
					CustomType:          supertypes.StringType{},
				},
				sentrydata.SnubaDatasets,
			),
			"environment": schema.StringAttribute{
				MarkdownDescription: "TODO",
				Optional:            true,
				CustomType:          supertypes.StringType{},
			},
			"event_types": schema.SetAttribute{
				MarkdownDescription: "TODO",
				Required:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
			"extrapolation_mode": tfutils.WithEnumStringAttribute(
				schema.StringAttribute{
					MarkdownDescription: "TODO",
					Optional:            true,
					Computed:            true,
					CustomType:          supertypes.StringType{},
				},
				sentrydata.ExtrapolationModes,
			),
			"issue_detection": schema.SingleNestedAttribute{
				MarkdownDescription: "The issue detection type configuration.",
				Required:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MetricMonitorResourceModelIssueDetection](ctx),
				Attributes: map[string]schema.Attribute{
					"type": tfutils.WithEnumStringAttribute(
						schema.StringAttribute{
							MarkdownDescription: "`static`: Threshold based monitor; `percent`: Change based monitor; `dynamic`: Dynamic monitor.",
							Required:            true,
							CustomType:          supertypes.StringType{},
						},
						sentrydata.AlertRuleDetectionTypes,
					),
					"comparison_delta": schema.Int64Attribute{
						MarkdownDescription: "TODO",
						Optional:            true,
						CustomType:          supertypes.Int64Type{},
					},
				},
			},
			"condition_group": schema.SingleNestedAttribute{
				MarkdownDescription: "TODO",
				Required:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[MetricMonitorResourceModelConditionGroup](ctx),
				Attributes: map[string]schema.Attribute{
					"logic_type": tfutils.WithEnumStringAttribute(
						schema.StringAttribute{
							MarkdownDescription: "TODO",
							Optional:            true,
							Computed:            true,
							Default:             stringdefault.StaticString("any"),
							CustomType:          supertypes.StringType{},
						},
						sentrydata.DataConditionGroupTypes,
					),
					"conditions": schema.ListNestedAttribute{
						MarkdownDescription: "TODO",
						Required:            true,
						CustomType:          supertypes.NewListNestedObjectTypeOf[MetricMonitorResourceModelConditionGroupConditionsItem](ctx),
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"type": tfutils.WithEnumStringAttribute(
									schema.StringAttribute{
										MarkdownDescription: "TODO",
										Required:            true,
										CustomType:          supertypes.StringType{},
									},
									sentrydata.DataConditionTypes,
								),
								"comparison": schema.Int64Attribute{
									MarkdownDescription: "TODO",
									Required:            true,
									CustomType:          supertypes.Int64Type{},
								},
								"condition_result": schema.Int64Attribute{
									MarkdownDescription: "TODO",
									Required:            true,
									CustomType:          supertypes.Int64Type{},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *MetricMonitorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data MetricMonitorResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	} else if body == nil {
		resp.Diagnostics.AddError("Provider Error", "getCreateJSONRequestBody returned a nil body")
		return
	}

	httpResp, err := r.apiClient.CreateProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Project.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON201)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MetricMonitorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data MetricMonitorResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.GetProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	responseData := httpResp.JSON200

	if responseData == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MetricMonitorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Update is not supported for this resource")
}

func (r *MetricMonitorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data MetricMonitorResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.DeleteProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

type MetricMonitorResourceModel struct {
	Id                supertypes.StringValue                                                          `tfsdk:"id"`
	Organization      supertypes.StringValue                                                          `tfsdk:"organization"`
	Project           supertypes.StringValue                                                          `tfsdk:"project"`
	Enabled           supertypes.BoolValue                                                            `tfsdk:"enabled"`
	Name              supertypes.StringValue                                                          `tfsdk:"name"`
	Description       supertypes.StringValue                                                          `tfsdk:"description"`
	DefaultAssignee   supertypes.SingleNestedObjectValueOf[MetricMonitorResourceModelDefaultAssignee] `tfsdk:"default_assignee"`
	Aggregate         supertypes.StringValue                                                          `tfsdk:"aggregate"`
	Dataset           supertypes.StringValue                                                          `tfsdk:"dataset"`
	Environment       supertypes.StringValue                                                          `tfsdk:"environment"`
	EventTypes        supertypes.SetValueOf[string]                                                   `tfsdk:"event_types"`
	ExtrapolationMode supertypes.StringValue                                                          `tfsdk:"extrapolation_mode"`
	IssueDetection    supertypes.SingleNestedObjectValueOf[MetricMonitorResourceModelIssueDetection]  `tfsdk:"issue_detection"`
	ConditionGroup    supertypes.SingleNestedObjectValueOf[MetricMonitorResourceModelConditionGroup]  `tfsdk:"condition_group"`
}

type MetricMonitorResourceModelDefaultAssignee struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}

type MetricMonitorResourceModelIssueDetection struct {
	Type            supertypes.StringValue `tfsdk:"type"`
	ComparisonDelta supertypes.Int64Value  `tfsdk:"comparison_delta"`
}

type MetricMonitorResourceModelConditionGroup struct {
	LogicType  supertypes.StringValue                                                                     `tfsdk:"logic_type"`
	Conditions supertypes.ListNestedObjectValueOf[MetricMonitorResourceModelConditionGroupConditionsItem] `tfsdk:"conditions"`
}

type MetricMonitorResourceModelConditionGroupConditionsItem struct {
	Type            supertypes.StringValue `tfsdk:"type"`
	Comparison      supertypes.Int64Value  `tfsdk:"comparison"`
	ConditionResult supertypes.Int64Value  `tfsdk:"condition_result"`
}
