// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &OrganizationResource{}
var _ resource.ResourceWithImportState = &OrganizationResource{}

func NewOrganizationResource() resource.Resource {
	return &OrganizationResource{}
}

type OrganizationResource struct {
	baseResource
}

func (r *OrganizationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization"
}

func (r *OrganizationResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Sentry Organization resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The unique URL slug for this organization.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The human readable name for the organization.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"slug": schema.StringAttribute{
				MarkdownDescription: "The unique URL slug for this organization.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"agree_terms": schema.BoolAttribute{
				MarkdownDescription: "You agree to the applicable terms of service and privacy policy. This is only used for creation.",
				Required:            true,
				CustomType:          supertypes.BoolType{},
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
			},
			"internal_id": schema.StringAttribute{
				MarkdownDescription: "The internal ID for this organization.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"is_early_adopter": schema.BoolAttribute{
				MarkdownDescription: "Opt-in to new features before they're released to the public.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"hide_ai_features": schema.BoolAttribute{
				MarkdownDescription: "Hide AI features from the organization.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"codecov_access": schema.BoolAttribute{
				MarkdownDescription: "Enable Code Coverage Insights. This feature is only available for organizations on the Team plan and above.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"default_role": schema.StringAttribute{
				MarkdownDescription: "The default role new members will receive. Valid values are `member`, `admin`, `manager`, `owner`.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"open_membership": schema.BoolAttribute{
				MarkdownDescription: "Allow organization members to freely join any team.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"events_member_admin": schema.BoolAttribute{
				MarkdownDescription: "Allow members to delete events by granting them the `event:admin` scope.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"alerts_member_write": schema.BoolAttribute{
				MarkdownDescription: "Allow members to create, edit, and delete alert rules by granting them the `alerts:write` scope.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"attachments_role": schema.StringAttribute{
				MarkdownDescription: "The role required to download event attachments. Valid values are `member`, `admin`, `manager`, `owner`.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"debug_files_role": schema.StringAttribute{
				MarkdownDescription: "The role required to download debug information files. Valid values are `member`, `admin`, `manager`, `owner`.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"avatar_type": schema.StringAttribute{
				MarkdownDescription: "The type of display picture for the organization. Valid values are `letter_avatar`, `upload`.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"avatar": schema.StringAttribute{
				MarkdownDescription: "The image to upload as the organization avatar, in base64. Required if `avatar_type` is `upload`.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
			},
			"require_2fa": schema.BoolAttribute{
				MarkdownDescription: "Require and enforce two-factor authentication for all members.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"allow_shared_issues": schema.BoolAttribute{
				MarkdownDescription: "Allow sharing of limited details on issues to anonymous users.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"enhanced_privacy": schema.BoolAttribute{
				MarkdownDescription: "Enable enhanced privacy controls to limit personally identifiable information (PII) as well as source code in things like notifications.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"scrape_javascript": schema.BoolAttribute{
				MarkdownDescription: "Allow Sentry to scrape missing JavaScript source context when possible.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"store_crash_reports": schema.Int64Attribute{
				MarkdownDescription: "How many native crash reports to store per issue. Valid values are `0`, `1`, `5`, `10`, `20`, `50`, `100`, `-1` (unlimited).",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"allow_join_requests": schema.BoolAttribute{
				MarkdownDescription: "Allow users to request to join your organization.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"data_scrubber": schema.BoolAttribute{
				MarkdownDescription: "Require server-side data scrubbing for all projects.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"data_scrubber_defaults": schema.BoolAttribute{
				MarkdownDescription: "Apply the default scrubbers to prevent things like passwords and credit cards from being stored for all projects.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"sensitive_fields": schema.ListAttribute{
				MarkdownDescription: "A list of additional global field names to match against when scrubbing data for all projects.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.NewListTypeOf[string](ctx),
			},
			"safe_fields": schema.ListAttribute{
				MarkdownDescription: "A list of global field names which data scrubbers should ignore.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.NewListTypeOf[string](ctx),
			},
			"scrub_ip_addresses": schema.BoolAttribute{
				MarkdownDescription: "Prevent IP addresses from being stored for new events on all projects.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"relay_pii_config": schema.StringAttribute{
				MarkdownDescription: "Advanced data scrubbing rules that can be configured for each project as a JSON string.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"trusted_relays": schema.ListNestedAttribute{
				MarkdownDescription: "A list of local Relays registered for the organization.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.NewListNestedObjectTypeOf[OrganizationResourceModelTrustedRelaysItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the relay.",
							Required:            true,
							CustomType:          supertypes.StringType{},
						},
						"public_key": schema.StringAttribute{
							MarkdownDescription: "The public key of the relay.",
							Required:            true,
							CustomType:          supertypes.StringType{},
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "A description for the relay.",
							Optional:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
			"github_pr_bot": schema.BoolAttribute{
				MarkdownDescription: "Allow Sentry to comment on recent pull requests suspected of causing issues.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"github_open_pr_bot": schema.BoolAttribute{
				MarkdownDescription: "Allow Sentry to comment on open pull requests to show recent error issues for the code being changed.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"github_nudge_invite": schema.BoolAttribute{
				MarkdownDescription: "Allow Sentry to detect users committing to your GitHub repositories that are not part of your Sentry organization.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"gitlab_pr_bot": schema.BoolAttribute{
				MarkdownDescription: "Allow Sentry to comment on recent pull requests suspected of causing issues.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
			"allow_member_project_creation": schema.BoolAttribute{
				MarkdownDescription: "Allow members to create projects.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.BoolType{},
			},
		},
	}
}

func (r *OrganizationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data OrganizationResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	} else if body == nil {
		resp.Diagnostics.AddError("Provider Error", "getCreateJSONRequestBody returned a nil body")
		return
	}

	httpResp, err := r.apiClient.CreateOrganizationWithResponse(ctx, *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON201)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data OrganizationResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.GetOrganizationWithResponse(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	responseData := httpResp.JSON200

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data OrganizationResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.UpdateOrganizationWithResponse(ctx, data.Id.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data OrganizationResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.DeleteOrganizationWithResponse(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

func (r *OrganizationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

type OrganizationResourceModel struct {
	Id                         supertypes.StringValue                                                         `tfsdk:"id"`
	Name                       supertypes.StringValue                                                         `tfsdk:"name"`
	Slug                       supertypes.StringValue                                                         `tfsdk:"slug"`
	AgreeTerms                 supertypes.BoolValue                                                           `tfsdk:"agree_terms"`
	InternalId                 supertypes.StringValue                                                         `tfsdk:"internal_id"`
	IsEarlyAdopter             supertypes.BoolValue                                                           `tfsdk:"is_early_adopter"`
	HideAiFeatures             supertypes.BoolValue                                                           `tfsdk:"hide_ai_features"`
	CodecovAccess              supertypes.BoolValue                                                           `tfsdk:"codecov_access"`
	DefaultRole                supertypes.StringValue                                                         `tfsdk:"default_role"`
	OpenMembership             supertypes.BoolValue                                                           `tfsdk:"open_membership"`
	EventsMemberAdmin          supertypes.BoolValue                                                           `tfsdk:"events_member_admin"`
	AlertsMemberWrite          supertypes.BoolValue                                                           `tfsdk:"alerts_member_write"`
	AttachmentsRole            supertypes.StringValue                                                         `tfsdk:"attachments_role"`
	DebugFilesRole             supertypes.StringValue                                                         `tfsdk:"debug_files_role"`
	AvatarType                 supertypes.StringValue                                                         `tfsdk:"avatar_type"`
	Avatar                     supertypes.StringValue                                                         `tfsdk:"avatar"`
	Require2fa                 supertypes.BoolValue                                                           `tfsdk:"require_2fa"`
	AllowSharedIssues          supertypes.BoolValue                                                           `tfsdk:"allow_shared_issues"`
	EnhancedPrivacy            supertypes.BoolValue                                                           `tfsdk:"enhanced_privacy"`
	ScrapeJavascript           supertypes.BoolValue                                                           `tfsdk:"scrape_javascript"`
	StoreCrashReports          supertypes.Int64Value                                                          `tfsdk:"store_crash_reports"`
	AllowJoinRequests          supertypes.BoolValue                                                           `tfsdk:"allow_join_requests"`
	DataScrubber               supertypes.BoolValue                                                           `tfsdk:"data_scrubber"`
	DataScrubberDefaults       supertypes.BoolValue                                                           `tfsdk:"data_scrubber_defaults"`
	SensitiveFields            supertypes.ListValueOf[string]                                                 `tfsdk:"sensitive_fields"`
	SafeFields                 supertypes.ListValueOf[string]                                                 `tfsdk:"safe_fields"`
	ScrubIpAddresses           supertypes.BoolValue                                                           `tfsdk:"scrub_ip_addresses"`
	RelayPiiConfig             supertypes.StringValue                                                         `tfsdk:"relay_pii_config"`
	TrustedRelays              supertypes.ListNestedObjectValueOf[OrganizationResourceModelTrustedRelaysItem] `tfsdk:"trusted_relays"`
	GithubPrBot                supertypes.BoolValue                                                           `tfsdk:"github_pr_bot"`
	GithubOpenPrBot            supertypes.BoolValue                                                           `tfsdk:"github_open_pr_bot"`
	GithubNudgeInvite          supertypes.BoolValue                                                           `tfsdk:"github_nudge_invite"`
	GitlabPrBot                supertypes.BoolValue                                                           `tfsdk:"gitlab_pr_bot"`
	AllowMemberProjectCreation supertypes.BoolValue                                                           `tfsdk:"allow_member_project_creation"`
}

type OrganizationResourceModelTrustedRelaysItem struct {
	Name        supertypes.StringValue `tfsdk:"name"`
	PublicKey   supertypes.StringValue `tfsdk:"public_key"`
	Description supertypes.StringValue `tfsdk:"description"`
}
