// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-sentry/internal/sentrydata"
	"github.com/jianyuan/terraform-provider-sentry/internal/tfutils"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &CronMonitorResource{}

func NewCronMonitorResource() resource.Resource {
	return &CronMonitorResource{}
}

type CronMonitorResource struct {
	baseResource
}

func (r *CronMonitorResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cron_monitor"
}

func (r *CronMonitorResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Create a Monitor for a Project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID to create the monitor for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "The project slug or internal ID to create the monitor for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of this monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "A description of the monitor. Will be used in the resulting issue.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
			},
			"checkin_margin": schema.Int64Attribute{
				MarkdownDescription: "Grace period. The number of minutes before a check-in is considered missed.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"failure_issue_threshold": schema.Int64Attribute{
				MarkdownDescription: "Failure tolerance. Create a new issue when this many consecutive missed or error check-ins are processed.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"max_runtime": schema.Int64Attribute{
				MarkdownDescription: "Maximum runtime. The number of minutes before an in-progress check-in is marked timed out.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"recovery_threshold": schema.Int64Attribute{
				MarkdownDescription: "Recovery Tolerance. Resolve the issue when this many consecutive healthy check-ins are processed.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"schedule": schema.SingleNestedAttribute{
				MarkdownDescription: "Set your schedule.",
				Required:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[CronMonitorResourceModelSchedule](ctx),
				Attributes: map[string]schema.Attribute{
					"crontab": schema.StringAttribute{
						MarkdownDescription: "Use the crontab syntax. (e.g. 0 0 * * *)",
						Optional:            true,
						CustomType:          supertypes.StringType{},
						Validators: []validator.String{
							stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("interval_value"), path.MatchRelative().AtParent().AtName("interval_unit")),
							stringvalidator.AtLeastOneOf(path.MatchRelative().AtParent().AtName("interval_value")),
							stringvalidator.AtLeastOneOf(path.MatchRelative().AtParent().AtName("interval_unit")),
						},
					},
					"interval_value": schema.Int64Attribute{
						MarkdownDescription: "",
						Optional:            true,
						CustomType:          supertypes.Int64Type{},
						Validators: []validator.Int64{
							int64validator.ConflictsWith(path.MatchRelative().AtParent().AtName("crontab")),
							int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("interval_unit")),
						},
					},
					"interval_unit": tfutils.WithEnumStringAttribute(
						schema.StringAttribute{
							MarkdownDescription: "",
							Optional:            true,
							CustomType:          supertypes.StringType{},
							Validators: []validator.String{
								stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("crontab")),
								stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("interval_value")),
							},
						},
						sentrydata.Intervals,
					),
				},
			},
			"timezone": tfutils.WithEnumStringAttribute(
				schema.StringAttribute{
					MarkdownDescription: "Timezone.",
					Optional:            true,
					Computed:            true,
					Default:             stringdefault.StaticString("UTC"),
					CustomType:          supertypes.StringType{},
				},
				sentrydata.Timezones,
			),
		},
	}
}

func (r *CronMonitorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CronMonitorResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.CreateProjectMonitorWithResponse(ctx, data.Organization.ValueString(), body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON201)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CronMonitorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CronMonitorResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.GetProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	responseData := httpResp.JSON200

	if responseData == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CronMonitorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Update is not supported for this resource")
}

func (r *CronMonitorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CronMonitorResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.DeleteProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

type CronMonitorResourceModel struct {
	Id                    supertypes.StringValue                                                 `tfsdk:"id"`
	Organization          supertypes.StringValue                                                 `tfsdk:"organization"`
	Project               supertypes.StringValue                                                 `tfsdk:"project"`
	Name                  supertypes.StringValue                                                 `tfsdk:"name"`
	Description           supertypes.StringValue                                                 `tfsdk:"description"`
	CheckinMargin         supertypes.Int64Value                                                  `tfsdk:"checkin_margin"`
	FailureIssueThreshold supertypes.Int64Value                                                  `tfsdk:"failure_issue_threshold"`
	MaxRuntime            supertypes.Int64Value                                                  `tfsdk:"max_runtime"`
	RecoveryThreshold     supertypes.Int64Value                                                  `tfsdk:"recovery_threshold"`
	Schedule              supertypes.SingleNestedObjectValueOf[CronMonitorResourceModelSchedule] `tfsdk:"schedule"`
	Timezone              supertypes.StringValue                                                 `tfsdk:"timezone"`
}

type CronMonitorResourceModelSchedule struct {
	Crontab       supertypes.StringValue `tfsdk:"crontab"`
	IntervalValue supertypes.Int64Value  `tfsdk:"interval_value"`
	IntervalUnit  supertypes.StringValue `tfsdk:"interval_unit"`
}
