// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-sentry/internal/sentrydata"
	"github.com/jianyuan/terraform-provider-sentry/internal/sentrytypes"
	"github.com/jianyuan/terraform-provider-sentry/internal/tfutils"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	fstringvalidator "github.com/orange-cloudavenue/terraform-plugin-framework-validators/stringvalidator"
)

var _ resource.Resource = &UptimeMonitorResource{}
var _ resource.ResourceWithImportState = &UptimeMonitorResource{}

func NewUptimeMonitorResource() resource.Resource {
	return &UptimeMonitorResource{}
}

type UptimeMonitorResource struct {
	baseResource
}

func (r *UptimeMonitorResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uptime_monitor"
}

func (r *UptimeMonitorResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "⚠️ This resource is currently in beta and may be subject to change. It is supported by [New Monitors and Alerts](https://docs.sentry.io/product/new-monitors-and-alerts/) and may not be viewable in the UI today.\n\nCreate an Uptime Monitor for a Project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The internal ID of this monitor.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "The organization slug or internal ID to create the monitor for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "The project slug or internal ID to create the monitor for.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the monitor is enabled. Defaults to true.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
				CustomType:          supertypes.BoolType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of this monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "A description of the monitor. Will be used in the resulting issue.",
				Optional:            true,
				CustomType:          supertypes.StringType{},
			},
			"default_assignee": schema.SingleNestedAttribute{
				MarkdownDescription: "Sentry will assign new issues to this assignee.",
				Optional:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[UptimeMonitorResourceModelDefaultAssignee](ctx),
				Attributes: map[string]schema.Attribute{
					"user_id": schema.StringAttribute{
						MarkdownDescription: "The user ID to assign new issues to. Conflicts with `team_id`.",
						Optional:            true,
						CustomType:          supertypes.StringType{},
						Validators: []validator.String{
							stringvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("team_id")),
							stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("team_id")),
						},
					},
					"team_id": schema.StringAttribute{
						MarkdownDescription: "The team internal ID to assign new issues to. Conflicts with `user_id`.",
						Optional:            true,
						CustomType:          supertypes.StringType{},
						Validators: []validator.String{
							stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("user_id")),
						},
					},
				},
			},
			"url": schema.StringAttribute{
				MarkdownDescription: "The URL to monitor.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"method": tfutils.WithEnumStringAttribute(
				schema.StringAttribute{
					MarkdownDescription: "The HTTP method to use for the request.",
					Required:            true,
					CustomType:          supertypes.StringType{},
				},
				sentrydata.UptimeSubscriptionSupportedHttpMethods,
			),
			"body": schema.StringAttribute{
				MarkdownDescription: "The request body to send. Only applicable for methods that support a body.",
				Optional:            true,
				CustomType:          sentrytypes.TrimmedStringType{},
				Validators: []validator.String{
					fstringvalidator.NullIfAttributeIsOneOf(path.MatchRoot("method"), []attr.Value{supertypes.NewStringValue("GET"), supertypes.NewStringValue("HEAD"), supertypes.NewStringValue("OPTIONS")}),
				},
			},
			"headers": schema.MapAttribute{
				MarkdownDescription: "The headers to send with the request.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.NewMapTypeOf[string](ctx),
			},
			"interval_seconds": tfutils.WithEnumInt64Attribute(
				schema.Int64Attribute{
					MarkdownDescription: "The amount of time between each uptime check request.",
					Required:            true,
					CustomType:          supertypes.Int64Type{},
				},
				sentrydata.UptimeSubscriptionIntervalSeconds,
			),
			"timeout_ms": schema.Int64Attribute{
				MarkdownDescription: "The request timeout in milliseconds.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"environment": schema.StringAttribute{
				MarkdownDescription: "Name of the environment to create uptime issues in.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"recovery_threshold": schema.Int64Attribute{
				MarkdownDescription: "Number of consecutive successful checks required to mark monitor as recovered. Defaults to 1.",
				Optional:            true,
				Computed:            true,
				Default:             int64default.StaticInt64(1),
				CustomType:          supertypes.Int64Type{},
			},
			"downtime_threshold": schema.Int64Attribute{
				MarkdownDescription: "Number of consecutive failed checks required to mark monitor as down. Defaults to 3.",
				Optional:            true,
				Computed:            true,
				Default:             int64default.StaticInt64(3),
				CustomType:          supertypes.Int64Type{},
			},
			"assertion_json": schema.StringAttribute{
				MarkdownDescription: "Define conditions that must be met for the check to be considered successful.",
				Optional:            true,
				CustomType:          jsontypes.NormalizedType{},
			},
		},
	}
}

func (r *UptimeMonitorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data UptimeMonitorResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	} else if body == nil {
		resp.Diagnostics.AddError("Provider Error", "getCreateJSONRequestBody returned a nil body")
		return
	}

	httpResp, err := r.apiClient.CreateProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Project.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON201 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON201)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UptimeMonitorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data UptimeMonitorResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.GetProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	responseData := httpResp.JSON200

	if responseData == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UptimeMonitorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data UptimeMonitorResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.UpdateProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UptimeMonitorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data UptimeMonitorResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.apiClient.DeleteProjectMonitorWithResponse(ctx, data.Organization.ValueString(), data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

func (r *UptimeMonitorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	first, second, third, err := tfutils.SplitThreePartId(req.ID, "organization", "project", "id")
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Error parsing ID: %s", err.Error()))
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(
		ctx, path.Root("organization"), first,
	)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(
		ctx, path.Root("project"), second,
	)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(
		ctx, path.Root("id"), third,
	)...)
}

type UptimeMonitorResourceModel struct {
	Id                supertypes.StringValue                                                          `tfsdk:"id"`
	Organization      supertypes.StringValue                                                          `tfsdk:"organization"`
	Project           supertypes.StringValue                                                          `tfsdk:"project"`
	Enabled           supertypes.BoolValue                                                            `tfsdk:"enabled"`
	Name              supertypes.StringValue                                                          `tfsdk:"name"`
	Description       supertypes.StringValue                                                          `tfsdk:"description"`
	DefaultAssignee   supertypes.SingleNestedObjectValueOf[UptimeMonitorResourceModelDefaultAssignee] `tfsdk:"default_assignee"`
	Url               supertypes.StringValue                                                          `tfsdk:"url"`
	Method            supertypes.StringValue                                                          `tfsdk:"method"`
	Body              sentrytypes.TrimmedString                                                       `tfsdk:"body"`
	Headers           supertypes.MapValueOf[string]                                                   `tfsdk:"headers"`
	IntervalSeconds   supertypes.Int64Value                                                           `tfsdk:"interval_seconds"`
	TimeoutMs         supertypes.Int64Value                                                           `tfsdk:"timeout_ms"`
	Environment       supertypes.StringValue                                                          `tfsdk:"environment"`
	RecoveryThreshold supertypes.Int64Value                                                           `tfsdk:"recovery_threshold"`
	DowntimeThreshold supertypes.Int64Value                                                           `tfsdk:"downtime_threshold"`
	AssertionJson     jsontypes.Normalized                                                            `tfsdk:"assertion_json"`
}

type UptimeMonitorResourceModelDefaultAssignee struct {
	UserId supertypes.StringValue `tfsdk:"user_id"`
	TeamId supertypes.StringValue `tfsdk:"team_id"`
}
