import type { Resource } from "../schema";

export default {
  name: "external_user",
  description: "Manages Sentry external user mappings.",
  api: {
    model: "ExternalUser",
    createMethod: "CreateOrganizationExternalUser",
    createRequestAttributes: ["organization"],
    readStrategy: "custom",
    updateMethod: "UpdateOrganizationExternalUser",
    updateRequestAttributes: ["organization", "internal_id"],
    deleteMethod: "DeleteOrganizationExternalUser",
    deleteRequestAttributes: ["organization", "internal_id"],
  },
  generate: {
    modelFillers: false,
  },
  importStateAttributes: ["organization", "internal_id"],
  attributes: [
    {
      name: "id",
      type: "string",
      description: "The organization/internal_id of this external user mapping.",
      computedOptionalRequired: "computed",
      planModifiers: ["stringplanmodifier.UseStateForUnknown()"],
      skipFill: true,
    },
    {
      name: "organization",
      type: "string",
      description: "The slug of the organization the resource belongs to.",
      computedOptionalRequired: "required",
      planModifiers: ["stringplanmodifier.RequiresReplace()"],
    },
    {
      name: "internal_id",
      type: "string",
      description:
        "The internal ID for this external user mapping (generated by Sentry).",
      computedOptionalRequired: "computed",
      planModifiers: ["stringplanmodifier.UseStateForUnknown()"],
      sourceAttribute: ["Id"],
    },
    {
      name: "user_id",
      type: "int64",
      description: "The user ID in Sentry.",
      computedOptionalRequired: "required",
    },
    {
      name: "external_name",
      type: "string",
      description: "The associated name for the provider.",
      computedOptionalRequired: "required",
    },
    {
      name: "external_provider",
      type: "string",
      description: 'The provider of the external actor (e.g., "gitlab").',
      computedOptionalRequired: "required",
      validators: [
        `stringvalidator.OneOf("github", "github_enterprise", "jira_server", "slack", "gitlab", "msteams", "custom_scm")`,
      ],
    },
    {
      name: "integration_id",
      type: "int64",
      description: "The Integration ID.",
      computedOptionalRequired: "required",
    },
    {
      name: "external_id",
      type: "string",
      description:
        "The external actor ID for the provider (e.g., GitLab User ID).",
      computedOptionalRequired: "required",
    },
  ],
} satisfies Resource;
