import dedent from "dedent";
import type { Resource } from "../schema";

export default {
  name: "organization_user_mapping",
  description: dedent.withOptions({ trimWhitespace: true })`
      Manages a mapping between a Sentry organization member and an external identity
      provider (for example GitHub, GitLab, Slack, or Jira Server).

      These mappings link Sentry users to identities in an installed organization
      integration so features such as issue assignment and commit attribution can
      resolve the correct person.

      ~> **Note:** Sentry does not expose a read API for external user mappings. After
      create or import, Terraform keeps the mapping attributes in state and does not
      refresh them from the API on subsequent plans.
    `,
  api: {
    model: "ExternalUser",
    createMethod: "CreateOrganizationExternalUser",
    createRequestAttributes: ["organization"],
    readStrategy: "custom",
    updateMethod: "UpdateOrganizationExternalUser",
    updateRequestAttributes: ["organization", "internal_id"],
    deleteMethod: "DeleteOrganizationExternalUser",
    deleteRequestAttributes: ["organization", "internal_id"],
  },
  generate: {
    modelFillers: false,
  },
  importStateAttributes: ["organization", "internal_id"],
  attributes: [
    {
      name: "id",
      type: "string",
      description:
        "The resource ID in the form `organization/internal_id`.",
      computedOptionalRequired: "computed",
      planModifiers: ["stringplanmodifier.UseStateForUnknown()"],
      skipFill: true,
    },
    {
      name: "organization",
      type: "string",
      description: "The slug of the organization the mapping belongs to.",
      computedOptionalRequired: "required",
      planModifiers: ["stringplanmodifier.RequiresReplace()"],
    },
    {
      name: "internal_id",
      type: "string",
      description:
        "The internal ID of this external user mapping (generated by Sentry).",
      computedOptionalRequired: "computed",
      planModifiers: ["stringplanmodifier.UseStateForUnknown()"],
      sourceAttribute: ["Id"],
    },
    {
      name: "user_id",
      type: "int64",
      description: "The Sentry user ID to map.",
      computedOptionalRequired: "required",
    },
    {
      name: "external_name",
      type: "string",
      description:
        "The display name of the identity in the external provider.",
      computedOptionalRequired: "required",
    },
    {
      name: "external_provider",
      type: "string",
      description:
        "The external identity provider. Valid values are `github`, `github_enterprise`, `jira_server`, `slack`, `gitlab`, `msteams`, and `custom_scm`.",
      computedOptionalRequired: "required",
      validators: [
        `stringvalidator.OneOf("github", "github_enterprise", "jira_server", "slack", "gitlab", "msteams", "custom_scm")`,
      ],
    },
    {
      name: "integration_id",
      type: "int64",
      description:
        "The ID of the organization integration for the external provider.",
      computedOptionalRequired: "required",
    },
    {
      name: "external_id",
      type: "string",
      description:
        "The actor ID in the external provider (for example a GitLab or GitHub user ID).",
      computedOptionalRequired: "required",
    },
  ],
} satisfies Resource;
