on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [freebsd, openbsd, solaris, windows, linux, darwin]
        goarch: [amd64, "386", arm, arm64]
        exclude:
          - goarch: "386"
            goos: solaris
          - goarch: arm
            goos: solaris
          - goarch: arm64
            goos: solaris
          - goarch: "386"
            goos: darwin
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: openbsd
          - goarch: arm64
            goos: openbsd

    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
