name: Update Sentry data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
      - uses: astral-sh/setup-uv@v8.2.0
      - uses: oven-sh/setup-bun@v2
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
      - run: go mod download
      - run: make generate
      - name: Commit generated changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Sentry data
